/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: {
          app:     '#0F1117',
          sidebar: '#0C0E14',
          card:    '#1A1D24',
          hover:   '#1E2230',
          input:   '#151820',
          popup:   '#1A1D24',
          active:  '#21253A',
        },
        brd: {
          subtle:  '#1E222E',
          default: '#2A2F3A',
          strong:  '#363C4A',
          focus:   '#7C6CF2',
          hover:   '#3A4D52',
        },
        tx: {
          primary:   '#EAEAF0',
          secondary: '#CBD5E1',
          muted:     '#9CA3AF',
          faint:     '#7B8494',
          inverse:   '#0F1117',
        },
        accent: {
          DEFAULT: '#7C6CF2',
          light:   '#9D8FF5',
          dim:     '#2D2960',
          bg:      '#1C1A38',
        },
        status: {
          green:   '#34D399',
          greenBg: '#0D2D1E',
          amber:   '#FBBF24',
          amberBg: '#2D2510',
          red:     '#F87171',
          redBg:   '#2D1515',
          blue:    '#60A5FA',
          blueBg:  '#0D1F38',
        },
        rize: {
          purple:  '#8B5CF6',
          purpleL: '#A78BFA',
          blue:    '#60A5FA',
          green:   '#34D399',
          amber:   '#FBBF24',
          red:     '#F87171',
          teal:    '#7C6CF2',
          pink:    '#F472B6',
        },
        session: {
          focus:   '#7C6CF2',
          meeting: '#F87171',
          break:   '#6B7280',
          design:  '#A78BFA',
          coding:  '#60A5FA',
          writing: '#FB923C',
          other:   '#60A5FA',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Consolas', 'Monaco', 'monospace'],
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px', letterSpacing: '0.01em' }],
        xs:    ['11px', { lineHeight: '16px' }],
        sm:    ['12px', { lineHeight: '18px' }],
        base:  ['13px', { lineHeight: '20px' }],
        md:    ['14px', { lineHeight: '22px' }],
        lg:    ['15px', { lineHeight: '24px' }],
        xl:    ['17px', { lineHeight: '26px' }],
        '2xl': ['20px', { lineHeight: '28px' }],
        '3xl': ['24px', { lineHeight: '32px' }],
        '4xl': ['30px', { lineHeight: '38px' }],
      },
      letterSpacing: {
        label:  '0.07em',
        wide:   '0.05em',
        wider:  '0.10em',
        widest: '0.14em',
      },
      borderRadius: {
        sm:    '4px',
        md:    '6px',
        lg:    '8px',
        xl:    '10px',
        '2xl': '14px',
        '3xl': '18px',
        '4xl': '24px',
      },
      boxShadow: {
        xs:    '0 1px 2px rgba(0,0,0,0.24)',
        sm:    '0 6px 18px rgba(0,0,0,0.20)',
        card:  '0 16px 38px rgba(0,0,0,0.18), inset 0 1px 0 rgba(255,255,255,0.04)',
        popup: '0 24px 80px rgba(0,0,0,0.46), 0 1px 4px rgba(0,0,0,0.36)',
        inner: 'inset 0 1px 0 rgba(255,255,255,0.04)',
      },
      animation: {
        'pulse-dot': 'pulse-dot 2s cubic-bezier(0.4,0,0.6,1) infinite',
        'fade-in':   'fade-in 0.15s ease-out',
        'slide-up':  'slide-up 0.18s ease-out',
        'scale-in':  'scale-in 0.14s cubic-bezier(0.34,1.4,0.64,1)',
      },
      keyframes: {
        'pulse-dot': {
          '0%,100%': { opacity: '1'   },
          '50%':     { opacity: '0.4' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(6px)' },
          to:   { opacity: '1', transform: 'translateY(0)'   },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.94)' },
          to:   { opacity: '1', transform: 'scale(1)'    },
        },
      },
    },
  },
  plugins: [],
};
