/**
 * Reasoning Orchestrator — v2
 * Master semantic intelligence coordinator.
 *
 * Enforces the full intelligence pipeline order and maintains reasoning
 * consistency across all engine stages. This is the single entry point
 * for all AI-generated content in Flow Ledger.
 *
 * Pipeline:
 *   raw telemetry
 *   ↓ telemetrySanitizer          — strip noise, normalize app names
 *   ↓ WorkflowManager             — manages workflow state and continuity [NEW]
 *   ↓ contextCompressionEngine    — compress to weighted workflow signals
 *   ↓ signalRankingEngine         — score and prioritize semantic signals
 *   ↓ behaviorInferenceEngine     — infer work mode and energy state
 *   ↓ featureGraphEngine          — identify active product features
 *   ↓ workflowStateEngine         — resolve workflow state

 *   ↓ workblockFusionEngine       — fuse fragments into semantic workblock (now operates on WorkflowManager segments) [MODIFIED]
 *   ↓ intentInferenceEngine       — infer WHY (not just what)
 *   ↓ humanizationEngine          — convert to natural workflow language
 *   ↓ narrativeSynthesisEngine    — semantic narrative synthesis
 *   ↓ event-ready output
 *
 * Use orchestrate() for full async pipeline, orchestrateSync() for real-time.
 */

import { sanitizeSessions }                  from './engines/telemetrySanitizer.js';

import { rankSignals, getTopPhrases, getMeaningfulTools } from './engines/signalRankingEngine.js';
import { compressContext }                   from './engines/contextCompressionEngine.js';
import { inferBehavior }                     from './engines/behaviorInferenceEngine.js';
import { updateAndQueryGraph }               from './engines/featureGraphEngine.js';
import { resolveWorkflowState }              from './engines/workflowStateEngine.js';
import { inferIntent }                       from './engines/intentInferenceEngine.js';
import { humanize }                          from './engines/humanizationEngine.js';
import { synthesize }                        from './engines/narrativeSynthesisEngine.js';

import { workflowManager }                     from './core/WorkflowManager.js';
import { fuseWorkblock }                     from './engines/workblockFusionEngine.js';
import { getEcosystem, classifyWorkflowType } from './engines/workflowSegmentationEngine.js';
import { contextFingerprint }                from './engines/contextCompressionEngine.js';
import { determineOwnership, buildDurationQualifier } from './engines/workflowOwnershipEngine.js';
import { validateNarrative, selectBestTitle, isAutoGeneratedContent } from './engines/narrativeQAEngine.js';

// ─── Pipeline Cache ───────────────────────────────────────────────────────────

const pipelineCache = new Map();
const CACHE_TTL_MS = 90 * 1000;   // 90-second TTL

function getCached(fp) {
  const entry = pipelineCache.get(fp);
  if (!entry || Date.now() - entry.ts > CACHE_TTL_MS) {
    pipelineCache.delete(fp);
    return null;
  }
  return entry.result;
}

function setCached(fp, result) {
  pipelineCache.set(fp, { result, ts: Date.now() });
  if (pipelineCache.size > 30) {
    const oldest = pipelineCache.keys().next().value;
    pipelineCache.delete(oldest);
  }
}

// ─── Core Pipeline Stages ─────────────────────────────────────────────────────

function runCorePipeline(autoSessions, project, client, sessionDurationMins) {
  // ── Stage 1: Sanitize ──────────────────────────────────────────────────────
  const { sessions: cleanSessions, stats: sanitizeStats } = sanitizeSessions(autoSessions);

  // ── Stage 2: Process activities with WorkflowManager ──────────────────────
  // This replaces the traditional segmentation and handles workflow continuity.
  let currentWorkflow = null;
  let isNewWorkflow = false;
  let workflowBreakReason = null;

  for (const session of cleanSessions) {
    const { workflow, isNew, breakReason } = workflowManager.processActivity(session, project);
    currentWorkflow = workflow;
    if (isNew) {
      isNewWorkflow = true;
      workflowBreakReason = breakReason;
    }
  }

  // If no active workflow after processing, use cleanSessions as a fallback for compression.
  const workflowActivities = currentWorkflow ? currentWorkflow.activities : cleanSessions;
  const compressed = compressContext(workflowActivities, { project, client });

  // ── Stage 4: Rank signals ─────────────────────────────────────────────────
  const ranking = rankSignals(compressed);

  // ── Stage 5: Infer behavior ───────────────────────────────────────────────
  const behaviorProfile = inferBehavior(compressed);

  // ── Stage 6: Feature graph (project-isolated) ─────────────────────────────
  const featureGraph = updateAndQueryGraph(compressed.features || [], { project });

  // ── Stage 7: Workflow state ───────────────────────────────────────────────
  const workflowState = resolveWorkflowState(compressed, behaviorProfile, null, featureGraph);

  // ── Stage 7b: Workflow ownership ──────────────────────────────────────────
  // Single source of truth for what the user was actually working on.
  // All downstream narrative engines must use this as primary context.
  const ownership = determineOwnership(currentWorkflow ? currentWorkflow.activities : cleanSessions, compressed, {
    project,
    client,
    behaviorProfile,
    workflowConfidence: currentWorkflow?.confidence ?? currentWorkflow?.ownershipScore ?? 0,
    activeWorkflow: currentWorkflow,
  });

  // Per-call verb usage tracker — prevents module-level state across sessions
  const _usedVerbs = [];

  // ── Stage 8: Build partial reasoning result (for workblock fusion) ────────
  const partialReasoning = {
    compressed,
    behaviorProfile,
    featureGraph,
    workflowState,
    ownership,
    continuityProfile: null,
    workMode:          behaviorProfile?.workMode?.primary || 'deep_implementation',
    productivityState: behaviorProfile?.productivityState || 'focused_work',
    isDeepWork:        behaviorProfile?.isDeepWork || false,
    isSustainedWork:   behaviorProfile?.isSustainedWork || false,
    primaryCategory:   compressed.primaryCategory,
    primaryApp:        compressed.primaryApp,
    topFeature:        featureGraph?.topFeature,
    sessionDurationMins: sessionDurationMins ?? compressed.totalActiveMins,
    project,
    client,
    _usedVerbs,
  };

  // Original segmentation is now handled by WorkflowManager.processActivity.
  // fuseWorkblock() still expects the older per-segment shape (topPhrases,
  // keywords, ecosystems, durationMins, workflowType) — derive those from
  // WorkflowManager's currentWorkflow instead of leaving them undefined,
  // which previously made every workblock silently fall back to the generic
  // "Focused Work" type regardless of actual tool usage.
  const workflowEcosystems = currentWorkflow
    ? [...new Set((currentWorkflow.context?.apps || []).map(a => getEcosystem(a.name)).filter(Boolean))]
    : [];
  const segments = currentWorkflow ? [{
    sessions: currentWorkflow.activities,
    semanticLabel: currentWorkflow.name,
    workflowId: currentWorkflow.id,
    locked: currentWorkflow.locked,
    confidence: currentWorkflow.confidence,
    supportingTools: currentWorkflow.supportingTools,
    topPhrases: getTopPhrases(ranking, 8).map(phrase => ({ phrase })),
    keywords: currentWorkflow.keywords || [],
    ecosystems: workflowEcosystems,
    durationMins: (currentWorkflow.lastActivityTime - currentWorkflow.startTime) / (1000 * 60),
    workflowType: classifyWorkflowType(workflowEcosystems),
  }] : [];
  const segmentStats = { input: cleanSessions.length, segments: segments.length, totalMins: currentWorkflow ? (currentWorkflow.lastActivityTime - currentWorkflow.startTime) / (1000 * 60) : 0 };

  // ── Stage 9: Workblock fusion [NEW] ───────────────────────────────────────
  // Fuses multiple segments into a unified semantic understanding.
  const fusedWorkblock = fuseWorkblock(segments, partialReasoning);

  // Build the full reasoning result (with fusion context)
  const reasoning = {
    ...partialReasoning,
    segments,
    segmentStats,
    fusedWorkblock,
    ownership,
    _usedVerbs,

    primaryIntent:     null,
    immediateTask:     null,
    overallConfidence: 0,
    intentResult:      null,
    sanitizeStats,
  };

  // ── Stage 10: Intent inference ────────────────────────────────────────────
  const intent = inferIntent(reasoning, ranking);
  reasoning.primaryIntent   = intent.objective || intent.narrativeHint;
  reasoning.immediateTask   = intent.topPhrases[0] || null;
  reasoning.intentResult    = intent;

  // ── Stage 11: Humanization ────────────────────────────────────────────────
  const humanized = humanize(intent, ranking, reasoning);
  reasoning.humanized = humanized;

  // ── Stage 12: Overall confidence ──────────────────────────────────────────
  const fusionBonus = fusedWorkblock?.fusionConfidence >= 0.6 ? 0.05 : 0;
  reasoning.overallConfidence = Math.round(
    Math.min(
      ranking.qualityScore * 0.25 +
      intent.confidence    * 0.40 +
      humanized.qualityScore * 0.25 +
      fusionBonus,
      0.97,
    ) * 100,
  ) / 100;

  return { reasoning, intent, ranking, humanized, fusedWorkblock };
}

// ─── Narrative Assembly ───────────────────────────────────────────────────────

function assembleOutput(reasoning, intent, humanized, fusedWorkblock, existing = {}, linkedTaskTitle = null) {
  const ownership = reasoning.ownership;
  const preserveManualTitle = hasMeaningfulManualTitle(existing.title);

  // ── Linked task override ──────────────────────────────────────────────────
  // A task assignment is explicit user input — it outranks every inferred or
  // synthesized candidate below. A manually-edited title still wins over it.
  if (!preserveManualTitle && linkedTaskTitle) {
    const preserveDesc  = isManuallyWrittenDesc(existing.description);
    const taskTitle      = buildLinkedTaskTitle(reasoning, linkedTaskTitle);
    const taskDesc       = preserveDesc ? existing.description : (humanized.description || '');
    const taskQaReport   = validateNarrative({ title: taskTitle, description: taskDesc }, ownership);
    if (taskQaReport.passes) {
      return {
        title:            taskTitle,
        description:      taskDesc,
        productivityNote: humanized.productivityNote,
        deepWorkLabel:    buildDeepWorkLabel(reasoning),
        titleSource:      'linked_task',
        descSource:       preserveDesc ? 'manual' : 'humanization',
        qualityScore:     0.96,
        qaReport:         taskQaReport,
      };
    }
    // Falls through to the normal humanization/synthesis flow below.
  }

  // Prefer fusion-sourced narratives when workblock fusion produced a strong result
  const fusionIsStrong = fusedWorkblock?.fusionConfidence >= 0.65 && fusedWorkblock?.fusedSubject;

  // If humanized output is high quality (or fusion gives us confidence boost), use it
  const humanizedQualityOk = humanized.qualityScore >= (fusionIsStrong ? 0.45 : 0.55);

  let candidateTitle, candidateDesc, titleSource, descSource, qualityScore;

  if (humanizedQualityOk) {
    const preserveTitle = hasMeaningfulManualTitle(existing.title);
    const preserveDesc  = isManuallyWrittenDesc(existing.description);

    candidateTitle  = preserveTitle ? existing.title : humanized.title;
    candidateDesc   = preserveDesc  ? existing.description : humanized.description;
    titleSource     = preserveTitle ? 'manual' : 'humanization';
    descSource      = preserveDesc  ? 'manual' : 'humanization';
    qualityScore    = humanized.qualityScore;
  } else {
    // Fall back to narrativeSynthesisEngine
    try {
      const synth = synthesize(reasoning, {
        title: existing.title,
        description: isManuallyWrittenDesc(existing.description) ? existing.description : '',
      });
      candidateTitle  = synth.title;
      candidateDesc   = synth.description;
      titleSource     = synth.titleSource || 'synthesis';
      descSource      = 'synthesis';
      qualityScore    = synth.titleConfidence || 0.5;
    } catch {
      candidateTitle  = humanized.title || buildFallbackTitle(reasoning);
      candidateDesc   = humanized.description || '';
      titleSource     = 'fallback';
      descSource      = 'fallback';
      qualityScore    = 0.3;
    }
  }

  // ── QA Gate: validate the candidate narrative before returning ────────────
  // If it fails, try alternatives in order before accepting the fallback.
  const qaReport = validateNarrative(
    { title: candidateTitle, description: candidateDesc },
    ownership,
  );

  if (!qaReport.passes && titleSource !== 'manual') {
    // Try synthesis as alternate if we were using humanization
    if (titleSource === 'humanization') {
      try {
        const synth = synthesize(reasoning, {
          title: existing.title,
          description: isManuallyWrittenDesc(existing.description) ? existing.description : '',
        });
        const synthQA = validateNarrative({ title: synth.title, description: synth.description }, ownership);
        if (synthQA.passes || synthQA.qualityScore > qaReport.qualityScore) {
          candidateTitle = synth.title;
          candidateDesc  = synth.description;
          titleSource    = synth.titleSource || 'synthesis';
          descSource     = 'synthesis';
          qualityScore   = synth.titleConfidence || 0.5;
        }
      } catch {}
    }

    // Last resort: ownership-based fallback title
    if (!candidateTitle || !validateNarrative({ title: candidateTitle }, ownership).passes) {
      candidateTitle = buildFallbackTitle(reasoning);
      titleSource    = 'fallback';
      qualityScore   = 0.35;
    }
  }

  return {
    title:            candidateTitle,
    description:      candidateDesc,
    productivityNote: humanized.productivityNote,
    deepWorkLabel:    buildDeepWorkLabel(reasoning),
    titleSource,
    descSource,
    qualityScore,
    qaReport,
  };
}

// ─── Guard Functions ──────────────────────────────────────────────────────────

const VAGUE_TITLE_RE = /^(auto\s*:|general|work|task|untitled|session|focus|new event|scheduled work|auto[- ]?tracked|computer time)$/i;

function hasMeaningfulManualTitle(title = '') {
  if (!title || title.trim().length < 4) return false;
  return !VAGUE_TITLE_RE.test(title.trim()) && !/^auto\s*:/i.test(title);
}

// isManuallyWrittenDesc: delegates to the shared isAutoGeneratedContent from narrativeQAEngine
// so this and sessionSummaryEngine.isAutoGeneratedDescription() use identical logic (L-02 / R-05).
function isManuallyWrittenDesc(desc = '') {
  if (!desc || desc.trim().length < 30) return false;
  return !isAutoGeneratedContent(desc);
}

function buildDeepWorkLabel(reasoning) {
  const { behaviorProfile, compressed } = reasoning;
  const mins = reasoning.sessionDurationMins || compressed?.totalActiveMins || 0;
  const sw = compressed?.contextSwitches || 0;
  if (mins >= 90 && sw < 5) return 'Deep Focus';
  if (mins >= 60 && sw < 12) return 'Focused Work';
  if (behaviorProfile?.isDeepWork) return 'Deep Work';
  if (mins >= 30) return 'Work Session';
  return 'Quick Session';
}

const WORK_MODE_VERBS = {
  deep_implementation: 'Implementing',
  debugging:           'Debugging',
  design_work:         'Designing',
  refactoring:         'Improving',
  code_review:         'Reviewing',
  research:            'Analyzing',
  planning:            'Planning',
  testing:             'Testing',
};

function buildFallbackTitle(reasoning) {
  // Use ownership subject when available — more specific than category labels
  if (reasoning.ownership?.subject && reasoning.ownership.confidence >= 0.45) {
    const verb = WORK_MODE_VERBS[reasoning.workMode] || 'Working on';
    return `${verb} ${reasoning.ownership.subject}`;
  }

  // Category-aware semantic fallbacks (never bare "Feature Development")
  const cat = reasoning.primaryCategory;
  const labels = {
    development: 'Feature Implementation',
    design:      'UI Design System',
    writing:     'Technical Documentation',
    research:    'Technical Analysis',
    planning:    'Architecture Planning',
  };
  return labels[cat] || 'Development Session';
}

// Linked task title is explicit, user-curated ground truth (the user assigned
// this session to that task). It outranks every inferred/synthesized title.
function buildLinkedTaskTitle(reasoning, linkedTaskTitle) {
  const verb = WORK_MODE_VERBS[reasoning.workMode] || 'Working on';
  return linkedTaskTitle.toLowerCase().startsWith(verb.toLowerCase())
    ? linkedTaskTitle
    : `${verb} ${linkedTaskTitle}`;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Full synchronous orchestration pipeline.
 * Safe for Electron main/renderer process (no async I/O in critical path).
 *
 * @param {Array}  autoSessions        - raw tracked sessions
 * @param {Object} [options]
 * @param {Object} options.project     - { id, name }
 * @param {Object} options.client      - { id, name }
 * @param {number} options.sessionDurationMins - actual session duration
 * @param {Object} options.existing    - { title, description } to preserve
 * @param {boolean} options.useContinuity - run continuity engine (heavier)
 * @param {string} [options.linkedTaskTitle] - explicit task assignment title;
 *   outranks every inferred/synthesized title when present (see eventContextAnalyzer.extractLinkedTaskTitle)
 * @returns {Object} orchestrationResult
 */
export function orchestrateSync(autoSessions = [], options = {}) {
  const {
    project            = null,
    client             = null,
    sessionDurationMins = null,
    existing           = {},
    useContinuity      = false,
    sessionId          = null,
    linkedTaskTitle    = null,
  } = options;

  if (!autoSessions.length) {
    return buildEmptyResult(existing);
  }

  // Check cache
  const { sessions: cleanForFP } = sanitizeSessions(autoSessions);
  const compForFP = compressContext(cleanForFP);
  // Cache key: fingerprint + project + session time window.
  // The time window (first/last auto-session start) ensures different focus sessions
  // never share a cache entry even when they involve the same apps and project.
  // Without this, sessions on the same day with identical app usage would all return
  // the first session's cached title and description (the duplication bug).
  // linkedTaskTitle is also included since re-assigning a session to a different
  // task must produce a fresh title rather than reusing a stale cached one.
  const firstTs = autoSessions[0]?.started_at ?? '';
  const lastTs  = autoSessions[autoSessions.length - 1]?.started_at ?? '';
  const sessionKey = sessionId || `${firstTs}_${lastTs}`;
  const fp = contextFingerprint(compForFP) + `|${project?.id || ''}|${sessionKey}|${linkedTaskTitle || ''}`;

  const cached = getCached(fp);
  if (cached) return cached;

  // Run pipeline
  const { reasoning, intent, ranking, humanized, fusedWorkblock } = runCorePipeline(
    autoSessions, project, client, sessionDurationMins,
  );

  // Optional: run continuity engine (updates localStorage)
  if (useContinuity) {
    try {
      const continuityProfile = analyzeContinuity(
        reasoning.compressed,
        reasoning.behaviorProfile,
        existing.title || '',
      );
      reasoning.continuityProfile = continuityProfile;
      reasoning.activeObjective   = continuityProfile?.activeObjective;
    } catch {}
  }

  // Assemble final output
  const output = assembleOutput(reasoning, intent, humanized, fusedWorkblock, existing, linkedTaskTitle);

  const result = {
    // Primary outputs
    ...output,

    // Full reasoning context (for advanced callers)
    reasoning,
    intent,
    ranking,
    humanized,

    // Quick-access shortcuts
    workMode:           reasoning.workMode,
    productivityState:  reasoning.productivityState,
    isDeepWork:         reasoning.isDeepWork,
    primaryCategory:    reasoning.primaryCategory,
    primaryApp:         reasoning.primaryApp,
    topFeature:         reasoning.topFeature,
    overallConfidence:  reasoning.overallConfidence,
    project,
    client,

    // Workblock fusion context (for advanced callers)
    fusedWorkblock,
    segments:           reasoning.segments || [],
    workflowType:       fusedWorkblock?.workflowType?.id || null,
    implementationPhase: fusedWorkblock?.implementationPhase?.phaseId || null,

    // Workflow ownership (single source of truth for what user was working on)
    ownership:          reasoning.ownership,
    ownershipSubject:   reasoning.ownership?.subject || null,
    ownershipSource:    reasoning.ownership?.attributionSource || null,
  };

  setCached(fp, result);
  return result;
}

/**
 * Async orchestration — runs continuity engine (localStorage) and is
 * safe for background/non-blocking contexts.
 */
export async function orchestrate(autoSessions = [], options = {}) {
  const sync = orchestrateSync(autoSessions, { ...options, useContinuity: false });

  // Run continuity asynchronously (touches localStorage)
  if (autoSessions.length > 0) {
    try {
      const continuityProfile = analyzeContinuity(
        sync.reasoning.compressed,
        sync.reasoning.behaviorProfile,
        options.existing?.title || '',
      );
      sync.reasoning.continuityProfile = continuityProfile;
    } catch {}
  }

  return sync;
}

function buildEmptyResult(existing) {
  return {
    title:           existing.title || '',
    description:     existing.description || '',
    productivityNote: '',
    deepWorkLabel:   'Quick Session',
    titleSource:     'manual',
    descSource:      'manual',
    qualityScore:    0,
    reasoning:       null,
    intent:          null,
    ranking:         null,
    humanized:       null,
    overallConfidence: 0,
  };
}

/**
 * Invalidate all pipeline cache entries.
 * Call when session data changes significantly.
 */
export function invalidateCache() {
  pipelineCache.clear();
}

/**
 * Get current pipeline cache size (for debugging).
 */
export function getCacheStats() {
  return { size: pipelineCache.size, maxSize: 30 };
}
