/* ─────────────────────────────────────────────────────────────────────────────
   exportUtils.js — professional report export helpers for Flow Ledger
   Supports: CSV (with metadata + section hierarchy) and PDF (browser print)
───────────────────────────────────────────────────────────────────────────── */

// ─── Formatters ───────────────────────────────────────────────────────────────

export function fmtH(s) {
  const h = (s || 0) / 3600;
  return h >= 10 ? `${h.toFixed(0)}h` : `${h.toFixed(1)}h`;
}

export function fmtDuration(s) {
  if (!s || s < 0) return '0m';
  const h = Math.floor(s / 3600), m = Math.floor((s % 3600) / 60);
  if (h === 0) return `${m}m`;
  if (m === 0) return `${h}h`;
  return `${h}h ${m}m`;
}

export function fmtMoney(v) {
  if (!v || v === 0) return '—';
  return `$${Number(v).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export function fmtPct(part, total) {
  if (!total) return '0%';
  return `${Math.round(((part || 0) / total) * 100)}%`;
}

export function fmtDate(ts) {
  if (!ts) return '—';
  return new Date(ts * 1000).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
}

export function fmtNow() {
  return new Date().toLocaleString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

export function fmtDateRange(fromTs, toTs) {
  const opts = { month: 'short', day: 'numeric', year: 'numeric' };
  return `${new Date(fromTs * 1000).toLocaleDateString('en-US', opts)} – ${new Date(toTs * 1000).toLocaleDateString('en-US', opts)}`;
}

// ─── CSV builder ──────────────────────────────────────────────────────────────

/** Wrap a value in quotes, escaping internal quotes — safe for any cell value. */
function cell(v) {
  if (v == null) return '""';
  const s = String(v);
  return `"${s.replace(/"/g, '""')}"`;
}

/**
 * Build a professional CSV string with metadata header and multiple sections.
 *
 * @param {string}   reportTitle  — e.g. "Flow Ledger — Focus Analytics"
 * @param {object}   meta         — { dateRange?, period?, filters?, generatedBy? }
 * @param {Section[]} sections    — see Section shape below
 *
 * Section shape:
 *   { title, subtitle?, kpis?:[{label,value}], headers?:string[], rows?:any[][], summary?:[string,string][] }
 */
export function buildCSV(reportTitle, meta, sections) {
  const lines = [];

  // ── Report header block ────────────────────────────────────────────────────
  lines.push(cell(reportTitle));
  lines.push(`${cell('Flow Ledger')},${cell('Professional Work Analytics Report')}`);
  lines.push(`${cell('Generated')},${cell(fmtNow())}`);
  if (meta.dateRange)   lines.push(`${cell('Date Range')},${cell(meta.dateRange)}`);
  if (meta.period)      lines.push(`${cell('Period')},${cell(meta.period)}`);
  if (meta.filters)     lines.push(`${cell('Active Filters')},${cell(meta.filters)}`);
  if (meta.generatedBy) lines.push(`${cell('Generated By')},${cell(meta.generatedBy)}`);
  lines.push('');

  // ── Sections ───────────────────────────────────────────────────────────────
  for (const sec of sections) {
    // Section title separator
    lines.push(cell(`═══ ${sec.title.toUpperCase()} ═══`));
    if (sec.subtitle) lines.push(`${cell('')},${cell(sec.subtitle)}`);
    lines.push('');

    // KPI summary rows (before the main table)
    if (sec.kpis?.length) {
      lines.push(cell('KEY METRICS'));
      for (const kpi of sec.kpis) {
        lines.push(`${cell(kpi.label)},${cell(kpi.value)}`);
      }
      lines.push('');
    }

    // Column headers + data rows
    if (sec.headers?.length) {
      lines.push(sec.headers.map(cell).join(','));
    }
    for (const row of (sec.rows || [])) {
      lines.push(row.map(cell).join(','));
    }

    // Summary key-value block (after the table)
    if (sec.summary?.length) {
      lines.push('');
      lines.push(cell('SECTION SUMMARY'));
      for (const [k, v] of sec.summary) {
        lines.push(`${cell(k)},${cell(v)}`);
      }
    }

    lines.push('');
    lines.push('');
  }

  // ── Footer ─────────────────────────────────────────────────────────────────
  lines.push(cell('─── END OF REPORT ───'));
  lines.push(`${cell('Confidential')},${cell('Generated by Flow Ledger · ' + fmtNow())}`);

  return lines.join('\n');
}

// ─── Download trigger ─────────────────────────────────────────────────────────

export function triggerDownload(content, filename, mimeType = 'text/csv;charset=utf-8;') {
  // BOM makes Excel on Windows open UTF-8 CSV correctly
  const bom  = mimeType.includes('csv') ? '﻿' : '';
  const blob = new Blob([bom + content], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function exportAsCSV(reportTitle, meta, sections, filename) {
  const csv = buildCSV(reportTitle, meta, sections);
  triggerDownload(csv, filename || `flow-ledger-${new Date().toISOString().split('T')[0]}.csv`);
}

// ─── PDF (print-ready HTML) ───────────────────────────────────────────────────

const PRINT_CSS = `
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
    font-size: 11.5px; color: #1e293b; background: #fff;
    padding: 44px 56px; line-height: 1.55;
  }

  /* ── Cover header ── */
  .rpt-header { margin-bottom: 32px; }
  .rpt-brand {
    font-size: 10px; font-weight: 800; text-transform: uppercase;
    letter-spacing: 0.12em; color: #7c6cf2; margin-bottom: 8px;
    display: flex; align-items: center; gap: 6px;
  }
  .rpt-brand::before {
    content: ''; display: inline-block; width: 18px; height: 3px;
    background: #7c6cf2; border-radius: 2px;
  }
  .rpt-title {
    font-size: 26px; font-weight: 900; color: #0f172a;
    letter-spacing: -0.5px; line-height: 1.2;
  }
  .rpt-subtitle { font-size: 13px; color: #64748b; margin-top: 6px; }

  /* ── Metadata bar ── */
  .rpt-meta {
    display: flex; flex-wrap: wrap; gap: 0;
    margin: 24px 0 40px;
    border: 1px solid #e2e8f0; border-radius: 10px; overflow: hidden;
  }
  .rpt-meta-item {
    flex: 1; min-width: 140px;
    padding: 14px 20px; background: #f8faff;
    border-right: 1px solid #e2e8f0;
  }
  .rpt-meta-item:last-child { border-right: none; }
  .rpt-meta-label {
    font-size: 9px; font-weight: 800; text-transform: uppercase;
    letter-spacing: 0.1em; color: #94a3b8; margin-bottom: 4px;
  }
  .rpt-meta-value { font-size: 12.5px; font-weight: 700; color: #1e293b; }

  /* ── KPI cards ── */
  .rpt-kpi-row {
    display: flex; flex-wrap: wrap; gap: 12px; margin-bottom: 24px;
  }
  .rpt-kpi {
    flex: 1; min-width: 130px;
    border: 1px solid #e2e8f0; border-radius: 10px;
    padding: 16px 18px; background: #f8faff;
    border-top: 3px solid #7c6cf2;
  }
  .rpt-kpi-value {
    font-size: 24px; font-weight: 900; color: #7c6cf2; line-height: 1;
  }
  .rpt-kpi-label {
    font-size: 9.5px; font-weight: 700; text-transform: uppercase;
    letter-spacing: 0.08em; color: #94a3b8; margin-top: 6px;
  }

  /* ── Section ── */
  .rpt-section { margin-bottom: 44px; page-break-inside: avoid; }
  .rpt-section-header {
    display: flex; align-items: baseline; gap: 12px;
    padding-bottom: 10px; margin-bottom: 18px;
    border-bottom: 2px solid #7c6cf2;
  }
  .rpt-section-title {
    font-size: 11px; font-weight: 900; text-transform: uppercase;
    letter-spacing: 0.10em; color: #7c6cf2;
  }
  .rpt-section-sub { font-size: 11px; color: #64748b; }

  /* ── Table ── */
  table { width: 100%; border-collapse: collapse; font-size: 11px; }
  thead tr { background: #f1f5f9; }
  th {
    text-align: left; padding: 9px 11px;
    font-size: 9.5px; font-weight: 800; text-transform: uppercase;
    letter-spacing: 0.07em; color: #475569;
    border-bottom: 2px solid #cbd5e1;
  }
  td { padding: 8px 11px; border-bottom: 1px solid #f1f5f9; color: #334155; }
  tbody tr:nth-child(even) td { background: #fafbff; }
  tbody tr:last-child td { border-bottom: none; }

  .rpt-summary-table { margin-top: 16px; max-width: 440px; }
  .rpt-summary-table td:first-child { font-weight: 700; color: #475569; width: 55%; }
  .rpt-summary-table td { background: transparent !important; }

  /* ── Footer ── */
  .rpt-footer {
    margin-top: 56px; padding-top: 16px;
    border-top: 1px solid #e2e8f0;
    display: flex; justify-content: space-between; align-items: center;
    font-size: 9.5px; color: #94a3b8;
  }
  .rpt-footer strong { color: #7c6cf2; }

  @media print {
    body { padding: 22px 32px; }
    .rpt-section { page-break-inside: avoid; }
    .rpt-kpi { break-inside: avoid; }
  }
`;


/**
 * Build a print-ready HTML document string.
 *
 * @param {string}   reportTitle
 * @param {object}   meta          — { dateRange, period, filters?, generatedBy? }
 * @param {Section[]} sections
 */
export function buildPrintHTML(reportTitle, meta, sections) {
  // ── Metadata bar ──────────────────────────────────────────────────────────
  const metaEntries = Object.entries(meta).filter(([, v]) => v != null && v !== '');
  const metaHtml = metaEntries.map(([k, v]) => `
    <div class="rpt-meta-item">
      <div class="rpt-meta-label">${k.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase())}</div>
      <div class="rpt-meta-value">${v}</div>
    </div>`).join('');

  // ── Sections ──────────────────────────────────────────────────────────────
  const sectionsHtml = sections.map(sec => {
    let inner = '';

    if (sec.kpis?.length) {
      inner += `<div class="rpt-kpi-row">
        ${sec.kpis.map(k => `
          <div class="rpt-kpi">
            <div class="rpt-kpi-value">${k.value}</div>
            <div class="rpt-kpi-label">${k.label}</div>
          </div>`).join('')}
      </div>`;
    }

    if (sec.headers?.length && sec.rows?.length) {
      const displayRows = sec.rows.slice(0, 500);
      inner += `<table>
        <thead><tr>${sec.headers.map(h => `<th>${h}</th>`).join('')}</tr></thead>
        <tbody>${displayRows.map(row =>
          `<tr>${row.map(c => `<td>${c ?? '—'}</td>`).join('')}</tr>`
        ).join('')}</tbody>
      </table>`;
      if (sec.rows.length > 500) {
        inner += `<p style="font-size:10px;color:#94a3b8;margin-top:8px">
          Showing 500 of ${sec.rows.length} rows — export CSV for full dataset.
        </p>`;
      }
    }

    if (sec.summary?.length) {
      inner += `<table class="rpt-summary-table">
        <tbody>${sec.summary.map(([k, v]) => `<tr><td>${k}</td><td>${v}</td></tr>`).join('')}</tbody>
      </table>`;
    }

    return `
      <div class="rpt-section">
        <div class="rpt-section-header">
          <div class="rpt-section-title">${sec.title}</div>
          ${sec.subtitle ? `<div class="rpt-section-sub">${sec.subtitle}</div>` : ''}
        </div>
        ${inner}
      </div>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${reportTitle}</title>
  <style>${PRINT_CSS}</style>
</head>
<body>
  <div class="rpt-header">
    <div class="rpt-brand">Flow Ledger · Work Analytics</div>
    <h1 class="rpt-title">${reportTitle}</h1>
    <p class="rpt-subtitle">Professional productivity report · Confidential</p>
  </div>
  <div class="rpt-meta">${metaHtml}</div>
  ${sectionsHtml}
  <div class="rpt-footer">
    <span><strong>Flow Ledger</strong> — Confidential &amp; Proprietary</span>
    <span>Generated ${fmtNow()}</span>
  </div>
  <script>window.onload = () => { setTimeout(() => window.print(), 500); }</script>
</body>
</html>`;
}

export function exportAsPDF(reportTitle, meta, sections) {
  const html = buildPrintHTML(reportTitle, meta, sections);
  const win  = window.open('', '_blank', 'width=960,height=720');
  if (!win) {
    // Fallback: insert into current page in a hidden iframe
    alert('Please allow pop-ups to export PDF, or use CSV export instead.');
    return;
  }
  win.document.write(html);
  win.document.close();
}
