/**
 * Event Writing Engine — v2
 * Generates enterprise-grade, human-like event titles and descriptions.
 * Designed to match the quality of Rize.io, Linear, and Notion AI.
 *
 * Core improvement: uses window title PHRASES as the primary subject source,
 * producing specific titles instead of generic fragments.
 */

import {
  CATEGORY_VERBS, WORK_SUBTYPES, normalize, capitalizeFirst, capitalizeWords,
  hasMeaningfulTitle, analyzeContext, parseIDETitle, cleanWindowTitle,
} from './eventContextAnalyzer.js';
import { orchestrateSync } from '../reasoningOrchestrator.js';
import { isAutoGeneratedDescription } from './sessionSummaryEngine.js';
import { INTENT_TYPES, inferDomain } from './intentInferenceEngine.js';
import { getDominantSessions } from './workflowDominanceEngine.js';
import { isGenericSubject, checkTitleRejectPatterns } from './genericKeywordFilter.js';
import { checkNarrativeQuality } from './narrativeQualityEngine.js';
import { inferAction } from './actionInferenceEngine.js';

// ─── Work Subtype → Verb Map ──────────────────────────────────────────────────
// Much richer than generic category verbs — each subtype gets specific verbs.

const SUBTYPE_VERBS = {
  debugging:    ['Debugging',    'Fixing',          'Troubleshooting', 'Resolving',    'Investigating'],
  testing:      ['Testing',      'Validating',      'Writing Tests for','QA Testing',   'Verifying'],
  refactoring:  ['Refactoring',  'Improving',       'Cleaning Up',     'Optimizing',   'Restructuring'],
  implementing: ['Implementing', 'Building',        'Developing',      'Engineering',  'Creating'],
  designing:    ['Designing',    'Crafting',        'Wireframing',     'Prototyping',  'Creating'],
  researching:  ['Researching',  'Exploring',       'Investigating',   'Studying',     'Analyzing'],
  reviewing:    ['Reviewing',    'Auditing',        'Evaluating',      'Inspecting',   'Analyzing'],
  deploying:    ['Deploying',    'Shipping',        'Releasing',       'Publishing',   'Launching'],
  planning:     ['Planning',     'Scoping',         'Mapping Out',     'Strategizing', 'Organizing'],
  documenting:  ['Documenting',  'Writing',         'Drafting',        'Authoring',    'Composing'],
  integrating:  ['Integrating',  'Connecting',      'Setting Up',      'Wiring Up',    'Configuring'],
  architecting: ['Architecting', 'Designing',       'Structuring',     'Planning'],
  configuring:  ['Configuring',  'Setting Up',      'Installing',      'Initializing'],
  migrating:    ['Migrating',    'Upgrading',       'Porting',         'Converting'],
};

// ─── Description Verb Phrases by Category ────────────────────────────────────

const DESC_VERB_PHRASES = {
  development: ['Worked on', 'Built', 'Developed', 'Implemented', 'Improved'],
  design:      ['Designed', 'Created', 'Refined', 'Worked on', 'Prototyped'],
  writing:     ['Wrote', 'Drafted', 'Documented', 'Composed', 'Worked on'],
  research:    ['Researched', 'Explored', 'Investigated', 'Studied', 'Analyzed'],
  meeting:     ['Discussed', 'Reviewed', 'Aligned on', 'Planned', 'Collaborated on'],
  planning:    ['Planned', 'Scoped', 'Mapped out', 'Organized', 'Strategized around'],
  email:       ['Managed', 'Processed', 'Responded to', 'Handled'],
  learning:    ['Studied', 'Learned about', 'Explored', 'Researched'],
  data:        ['Analyzed', 'Processed', 'Built reports for', 'Reviewed'],
};

// ─── Learning / History Store ─────────────────────────────────────────────────

const WRITING_MEMORY_KEY = 'fl_event_writing_v2';

function loadWritingMemory() {
  try {
    const raw = localStorage.getItem(WRITING_MEMORY_KEY);
    return raw ? JSON.parse(raw) : { patterns: {}, accepted: {}, recentTitles: [] };
  } catch {
    return { patterns: {}, accepted: {}, recentTitles: [] };
  }
}

function saveWritingMemory(memory) {
  try {
    localStorage.setItem(WRITING_MEMORY_KEY, JSON.stringify(memory));
  } catch {}
}

export function recordTitleFeedback(contextKey, generatedTitle, finalTitle, accepted) {
  const mem = loadWritingMemory();
  if (accepted) {
    mem.accepted[contextKey] = generatedTitle;
  } else {
    if (finalTitle && finalTitle !== generatedTitle) {
      mem.patterns[contextKey] = finalTitle;
    }
  }
  // Keep recent titles for consistency
  if (finalTitle && hasMeaningfulTitle(finalTitle)) {
    mem.recentTitles = [finalTitle, ...mem.recentTitles.filter(t => t !== finalTitle)].slice(0, 30);
  }
  saveWritingMemory(mem);
}

function getLearnedTitle(contextKey) {
  const mem = loadWritingMemory();
  return mem.patterns[contextKey] || mem.accepted[contextKey] || null;
}

// ─── Context Fingerprint ──────────────────────────────────────────────────────

function buildContextKey(context) {
  const cat  = context.primaryCategory || 'unknown';
  const app  = normalize(context.primaryApp || '').slice(0, 10);
  const proj = context.project?.id || 'noproj';
  const sub  = context.workSubtype || 'general';
  return `${cat}:${app}:${proj}:${sub}`;
}

// ─── Verb Selection ───────────────────────────────────────────────────────────

/**
 * Pick the most specific verb for the context.
 * Priority: detected work subtype > category verbs > fallback
 */
function selectVerb(context, position = 0) {
  const { workSubtype, primaryCategory, fallbackKeywords = [], hour = 9 } = context;

  // Work subtype gives most specific verbs
  if (workSubtype && SUBTYPE_VERBS[workSubtype]) {
    return SUBTYPE_VERBS[workSubtype][position % SUBTYPE_VERBS[workSubtype].length];
  }

  // Fallback keyword scan
  const text = fallbackKeywords.join(' ');
  if (text.includes('debug') || text.includes('fix') || text.includes('bug'))     return 'Fixing';
  if (text.includes('refactor') || text.includes('cleanup'))                        return 'Refactoring';
  if (text.includes('review') || text.includes('audit'))                           return 'Reviewing';
  if (text.includes('test') || text.includes('spec'))                              return 'Testing';
  if (text.includes('deploy') || text.includes('release') || text.includes('ship')) return 'Deploying';
  if (text.includes('setup') || text.includes('config') || text.includes('init'))  return 'Setting Up';
  if (text.includes('doc') || text.includes('readme') || text.includes('wiki'))    return 'Documenting';
  if (text.includes('plan') || text.includes('roadmap') || text.includes('sprint')) return 'Planning';
  if (text.includes('research') || text.includes('explore'))                       return 'Researching';
  if (text.includes('migrat'))                                                     return 'Migrating';
  if (text.includes('integrat'))                                                   return 'Integrating';

  // Category default
  const verbs = CATEGORY_VERBS[primaryCategory] || CATEGORY_VERBS.research;
  const isMorning = hour >= 5 && hour < 12;
  const isEvening = hour >= 17;
  const idx = isMorning ? 0 : isEvening ? Math.min(2, verbs.length - 1) : 1;
  return verbs[Math.min(idx + position, verbs.length - 1)] || verbs[0];
}

// ─── Subject Extraction ───────────────────────────────────────────────────────

/**
 * Extract the best subject phrase for the title.
 *
 * Priority order:
 * 1. Cleaned window title phrases (most specific and human-readable)
 * 2. IDE file path → component name
 * 3. Project + keyword phrase
 * 4. Primary website topic
 * 5. Project name alone
 * 6. Category-based fallback
 */
function extractSubject(context) {
  const {
    windowTitlePhrases = [], bestWindowTitle, project, primaryCategory,
    apps = [], websites, primarySiteTopic, fallbackKeywords = [], workSubtype,
  } = context;

  // ── 1. Best window title phrase ──────────────────────────────────────────
  // Guard: never use a phrase that contains a URL, system path, or executable
  const DIRTY_PHRASE_RE = /https?:\/\/|[A-Z]:\\|\.exe(\s|$)|system32|\(\d+\)/i;

  // Also exclude phrases whose entire content is generic app terminology
  // e.g. "productivity", "dashboard", "system overview" should never become subjects.
  const cleanPhrases = windowTitlePhrases.filter(p =>
    !DIRTY_PHRASE_RE.test(p.phrase) && !isGenericSubject(p.phrase)
  );

  if (cleanPhrases.length) {
    const best = cleanPhrases[0];
    const phrase = best.phrase;

    // If the phrase starts with a verb, extract just the object part
    const VERB_STARTS = /^(building|implementing|designing|creating|developing|fixing|debugging|testing|writing|researching|refactoring|reviewing|planning|deploying|migrating|integrating|architecting|improving|adding|updating|configuring|setting up|working on|exploring)\s+/i;
    const verbMatch = phrase.match(VERB_STARTS);
    if (verbMatch) {
      const object = phrase.slice(verbMatch[0].length).trim();
      if (object.length > 4) {
        return { subject: capitalizeWords(object), verbOverride: capitalizeFirst(verbMatch[1]), source: 'window_title_verb' };
      }
    }

    // Check if it looks like an IDE window title (file.ext — project)
    const ideParsed = parseIDETitle(phrase);
    if (ideParsed?.file && ideParsed.file.length > 3) {
      const subj = project?.name
        ? `${project.name} ${ideParsed.file}`
        : ideParsed.file;
      return { subject: subj, verbOverride: null, source: 'ide_title' };
    }

    // Use the phrase directly if it's meaningful
    if (phrase.length > 5 && best.score > 15) {
      // Only prepend project name when the phrase is a short generic noun (≤3 words)
      // AND the phrase doesn't already imply a specific context.
      // Never prepend if: phrase is an AI topic, has action verb, or is already project-specific.
      const isAITopic = context.aiTopics?.some(t => t.phrase === phrase);
      const hasVerb = /^(building|implementing|fixing|debugging|testing|researching|planning|designing|reviewing|deploying|migrating|refactoring)/i.test(phrase);
      const wordCount = phrase.split(/\s+/).length;
      const isShortGeneric = wordCount <= 3 && !hasVerb && !isAITopic;

      if (project?.name && isShortGeneric &&
          !phrase.toLowerCase().includes(normalize(project.name))) {
        return { subject: `${project.name} — ${phrase}`, verbOverride: null, source: 'window_title_with_project' };
      }
      return { subject: capitalizeWords(phrase), verbOverride: null, source: isAITopic ? 'ai_topic' : 'window_title' };
    }
  }

  // ── 2. Website topic ────────────────────────────────────────────────────
  if (primarySiteTopic && primarySiteTopic.length > 3) {
    if (project?.name) {
      return { subject: `${project.name} via ${primarySiteTopic}`, verbOverride: null, source: 'site_topic' };
    }
    return { subject: primarySiteTopic, verbOverride: null, source: 'site_topic' };
  }

  // ── 3. Project + meaningful keyword ────────────────────────────────────
  // Exclude browser/app names that add no semantic value to a title
  const NOISE_KEYWORDS = new Set([
    'chrome', 'safari', 'firefox', 'edge', 'arc', 'brave', 'opera',
    'gmail', 'mail', 'inbox', 'photos', 'files', 'finder', 'explorer',
    'https', 'http', 'localhost', 'www', 'google', 'bing', 'yahoo',
  ]);

  if (project?.name) {
    const goodKeyword = fallbackKeywords.find(kw =>
      kw.length > 5 &&
      !normalize(project.name).includes(kw) &&
      !NOISE_KEYWORDS.has(kw)
    );
    if (goodKeyword) {
      return {
        subject: `${project.name} ${capitalizeWords(goodKeyword)}`,
        verbOverride: null,
        source: 'project_keyword',
      };
    }
    // Project name alone is fine — don't append bad keywords
    return { subject: project.name, verbOverride: null, source: 'project_only' };
  }

  // ── 4. App-based fallback ───────────────────────────────────────────────
  const topApp = apps[0];
  if (topApp) {
    const catLabel = {
      development: 'Development',
      design: 'Design',
      writing: 'Documentation',
      research: 'Research',
      planning: 'Planning',
    }[primaryCategory] || 'Work';
    return { subject: catLabel, verbOverride: null, source: 'fallback' };
  }

  return { subject: null, verbOverride: null, source: 'none' };
}

// ─── Title Quality Check ──────────────────────────────────────────────────────

const VAGUE_TITLE_WORDS = new Set([
  'auto', 'general', 'work', 'task', 'untitled', 'session', 'focus',
  'tracked', 'computer', 'time', 'new', 'event', 'unknown',
]);

function isQualityTitle(title = '') {
  if (!title || title.length < 8) return false;
  const words = normalize(title).split(/\s+/);
  // All words are vague → bad
  if (words.every(w => VAGUE_TITLE_WORDS.has(w))) return false;
  // Starts with "Auto:" → bad
  if (/^auto\s*:/i.test(title)) return false;
  // Only an app name → bad
  if (/^(claude|chatgpt|vscode|figma|notion|chrome|firefox|auto)\s*:?$/i.test(title.trim())) return false;
  // Auto-reject patterns: "Inspecting Productivity", "Reviewing Dashboard" etc.
  if (checkTitleRejectPatterns(title).rejected) return false;
  // Subject is all-generic app terminology
  const withoutVerb = title.replace(/^[A-Za-z]+ing\s+/i, '').replace(/^[A-Za-z]+ed\s+/i, '').trim();
  if (withoutVerb && isGenericSubject(withoutVerb)) return false;
  return true;
}

/**
 * Deduplicate adjacent repeated words in a title.
 * "Flow Ledger Flow Ledger" → "Flow Ledger"
 */
function deduplicateTitle(title = '') {
  const words = title.split(/\s+/);
  const result = [];
  for (let i = 0; i < words.length; i++) {
    if (i === 0 || normalize(words[i]) !== normalize(words[i - 1])) {
      result.push(words[i]);
    }
  }
  // Also check for repeated bigrams
  const joined = result.join(' ');
  return joined.replace(/(\b\w+\s+\w+\b)\s+\1/gi, '$1');
}

// ─── Main Title Generator ─────────────────────────────────────────────────────

/**
 * Generate a high-quality, specific event title from context.
 * Uses window title phrases as the primary source of truth.
 *
 * @param {Object} context
 * @param {Object|null} [precomputedInference] - Optional result from a prior
 *   inferAction() call (e.g. from humanizationEngine on the orchestrator path).
 *   When provided, Priority 0 skips the inferAction() call entirely, preventing
 *   the double-inference problem (R-04). Pass null to compute fresh (standalone path).
 */
export function generateTitle(context, precomputedInference = null) {
  const { primaryCategory, project, hour } = context;

  // Check learned title first
  const contextKey = buildContextKey(context);
  const learned = getLearnedTitle(contextKey);
  if (learned && isQualityTitle(learned)) {
    return {
      title: learned, confidence: 0.95, source: 'learned',
      alternates: [], contextKey,
    };
  }

  // ── Priority 0: Action Inference Engine ──────────────────────────────────
  // Use the precomputed inference when available (orchestrator path already ran
  // inferAction inside humanizationEngine — reusing avoids the double call).
  // On the standalone path (precomputedInference === null), compute fresh.
  const workModePrimary = context.workSubtype || 'deep_implementation';
  const inferred = precomputedInference ?? inferAction(
    {
      titlePhrases: context.windowTitlePhrases || [],
      aiConversationTopics: context.aiTopics || [],
      apps: context.apps || [],
      keywords: context.fallbackKeywords || [],
    },
    { workMode: { primary: workModePrimary } },
    { project }
  );

  let inferredTitle = null;
  let inferredSource = null;
  if (inferred.hasSubject && inferred.confidence >= 0.80 &&
      !['work_mode_fallback', 'primary_app'].includes(inferred.source)) {
    const candidateTitle = `${inferred.verb} ${inferred.subject}`;
    if (isQualityTitle(candidateTitle)) {
      inferredTitle = candidateTitle;
      inferredSource = inferred.source;
    }
  }

  // Extract subject and optional verb override
  const { subject, verbOverride, source } = extractSubject(context);

  // Select action verb
  const verb = verbOverride || selectVerb(context, 0);

  // Build the title — prefer action-inferred title when available
  let title = '';
  if (inferredTitle) {
    title = inferredTitle;
  } else if (subject) {
    // If subject already starts with the verb, don't repeat it
    if (normalize(subject).startsWith(normalize(verb))) {
      title = capitalizeWords(subject);
    } else {
      title = `${verb} ${subject}`;
    }
  } else {
    // Absolute fallback
    const catLabel = {
      development: 'Feature Development',
      design: 'UI Design Work',
      writing: 'Documentation',
      research: 'Research Session',
      planning: 'Sprint Planning',
      meeting: 'Team Meeting',
    }[primaryCategory] || 'Focus Session';
    title = `${verb} ${catLabel}`;
  }

  // Trim to 65 chars
  title = deduplicateTitle(title);
  if (title.length > 65) title = title.slice(0, 62).trim() + '…';

  // Quality check — if title is still bad, use better fallback
  if (!isQualityTitle(title)) {
    // Try domain-elevated fallback first (more informative than bare project name)
    const DOMAIN_ELEVATIONS = {
      'ai': 'AI Intelligence Systems', reasoning: 'Contextual Reasoning',
      semantic: 'Semantic Intelligence', session: 'Session Intelligence',
      analytics: 'Analytics Pipeline', workflow: 'Workflow Intelligence',
      calendar: 'Calendar Intelligence', tracking: 'Activity Tracking',
      performance: 'Performance Optimization', auth: 'Authentication System',
    };
    const domainHint = (context.fallbackKeywords || [])
      .map(kw => DOMAIN_ELEVATIONS[kw.toLowerCase()])
      .find(Boolean);

    if (domainHint) {
      title = `${selectVerb(context, 1)} ${domainHint}`;
    } else if (project?.name) {
      // Try action-inference on the broader context with quality guard
      const inferred2 = inferAction(
        {
          titlePhrases: context.windowTitlePhrases || [],
          aiConversationTopics: context.aiTopics || [],
          apps: context.apps || [],
          keywords: context.fallbackKeywords || [],
        },
        { workMode: { primary: context.workSubtype || 'deep_implementation' } },
        { project },
      );
      const candidate2 = inferred2.hasSubject ? `${inferred2.verb} ${inferred2.subject}` : null;
      title = (candidate2 && isQualityTitle(candidate2))
        ? candidate2
        : `${selectVerb(context, 1)} ${project.name}`;
    } else {
      const catLabel = {
        development: 'Feature Development',
        design: 'UI Design Work',
        writing: 'Documentation',
        research: 'Research Session',
        planning: 'Sprint Planning',
      }[primaryCategory] || 'Focus Session';
      title = `${selectVerb(context, 1)} ${catLabel}`;
    }
  }

  // Build 2 alternates with different verbs
  const altVerb1 = selectVerb(context, 1);
  const altVerb2 = selectVerb(context, 2);
  const altSubject = subject || project?.name || 'Work';
  const alternates = [
    deduplicateTitle(`${altVerb1} ${altSubject}`).slice(0, 65),
    deduplicateTitle(`${altVerb2} ${altSubject}`).slice(0, 65),
  ].filter(t => t !== title && isQualityTitle(t));

  // Confidence scoring — action-inference sources get elevated confidence
  const activeSource = inferredSource || source;
  let confidence = 0.45;
  if (inferredSource === 'ai_topic_verb')    confidence = 0.95;
  else if (inferredSource === 'ai_topic_subject') confidence = 0.90;
  else if (inferredSource === 'window_title_verb') confidence = 0.93;
  else if (inferredSource === 'ide_filename') confidence = 0.90;
  else if (source === 'ai_topic')              confidence = 0.94;
  else if (source === 'window_title_verb') confidence = 0.92;
  else if (source === 'ide_title')         confidence = 0.90;
  else if (source === 'window_title')      confidence = 0.85;
  else if (source === 'window_title_with_project') confidence = 0.80;
  else if (source === 'site_topic')        confidence = 0.70;
  else if (source === 'project_keyword')   confidence = 0.65;
  else if (source === 'project_only')      confidence = 0.55;
  if (project) confidence = Math.min(confidence + 0.03, 0.97);

  return {
    title,
    confidence: Math.round(confidence * 100) / 100,
    source: activeSource,
    alternates,
    contextKey,
    verb,
    subject: subject || '',
  };
}

// ─── Description Generator ────────────────────────────────────────────────────

/**
 * Generate a natural, professional description from context.
 * Reads like it was written by a person, not a template engine.
 */
export function generateDescription(context, generatedTitle = '') {
  const {
    primaryCategory, project, client, apps, websites,
    fallbackKeywords = [], durationMins, focusQuality, isDeepWork,
    windowTitlePhrases = [], workSubtype, contextSwitches, aiTopics = [],
  } = context;

  const parts = [];

  // ── 1. Main action clause ────────────────────────────────────────────────
  // Pick verb based on work subtype first, then category
  const SUBTYPE_DESC_VERBS = {
    debugging:    'Debugged',
    testing:      'Tested and validated',
    refactoring:  'Refactored',
    implementing: 'Implemented',
    designing:    'Designed',
    researching:  'Researched',
    reviewing:    'Reviewed',
    deploying:    'Deployed',
    planning:     'Planned',
    documenting:  'Documented',
    integrating:  'Integrated',
    architecting: 'Architected',
    configuring:  'Configured',
    migrating:    'Migrated',
  };
  const descVerbs = DESC_VERB_PHRASES[primaryCategory] || DESC_VERB_PHRASES.development;
  const descVerb = (workSubtype && SUBTYPE_DESC_VERBS[workSubtype]) || descVerbs[0];

  // What was worked on — derive from AI-generated title by stripping the leading verb
  let subject = '';
  const isVagueGenerated = !generatedTitle || /^auto\s*:/i.test(generatedTitle) || generatedTitle.length < 5;

  if (!isVagueGenerated) {
    subject = generatedTitle
      .replace(/^(Building|Implementing|Developing|Designing|Creating|Engineering|Coding|Fixing|Debugging|Troubleshooting|Testing|Validating|Refactoring|Optimizing|Researching|Exploring|Reviewing|Auditing|Inspecting|Evaluating|Assessing|Analyzing|Examining|Planning|Documenting|Drafting|Writing|Migrating|Deploying|Integrating|Architecting|Improving|Shipping|Configuring|Setting Up|Cleaning Up|Mapping Out|Scoping)\s+/i, '')
      .trim();
  }

  // Reject vague, auto-prefixed, URL-containing, system-path subjects
  const VAGUE_SUBJECT_RE = /^(auto\s*:|auto\s*-|general|work|task|untitled|session|focus|chrome|firefox|safari|arc|brave|edge|new tab)/i;
  const DIRTY_SUBJECT_RE = /https?:\/\/|[A-Z]:\\Windows|\.exe(\s|$)|c:\\windows|system32|\(\d+\)/i;

  if (!subject || VAGUE_SUBJECT_RE.test(subject) || DIRTY_SUBJECT_RE.test(subject) || subject.length < 4) subject = '';

  // Fallback 1: best window title phrase (noise-filtered by extractWindowTitlePhrases)
  if (!subject && windowTitlePhrases.length) {
    for (const p of windowTitlePhrases) {
      const cand = p.phrase;
      if (!VAGUE_SUBJECT_RE.test(cand) && !DIRTY_SUBJECT_RE.test(cand) &&
          cand.length >= 5 && !isGenericSubject(cand)) {
        subject = cand;
        break;
      }
    }
  }

  // Fallback 2: project name
  if (!subject && project?.name) {
    subject = project.name;
  }

  // Final safety: never let a dirty or vague subject through
  if (!subject || VAGUE_SUBJECT_RE.test(subject) || DIRTY_SUBJECT_RE.test(subject)) {
    subject = project?.name || null;
  }

  if (subject) {
    parts.push(`${descVerb} ${subject}`);
  } else {
    // No meaningful subject — use a category-level description
    const catDescriptions = {
      development: 'development and engineering work',
      design: 'design and UX work',
      writing: 'writing and documentation',
      research: 'research and exploration',
      planning: 'planning and organization',
    };
    const catDesc = catDescriptions[primaryCategory] || 'focused work';
    parts.push(`${descVerb.replace(/^Worked on$/, 'Completed')} ${catDesc}`);
  }

  // ── 2. Specific activity detail (single focused phrase only) ────────────
  // Use one clean secondary phrase when it genuinely extends the primary subject.
  // Never chain multiple phrases ("covering X and Y") — it creates audit-report language.
  const additionalPhrases = windowTitlePhrases
    .slice(1, 5)
    .filter(p => p.phrase !== windowTitlePhrases[0]?.phrase)
    .map(p => {
      const clean = p.phrase.replace(/^(building|implementing|designing|creating|developing|fixing|debugging|testing|writing|researching|reviewing|planning|inspecting|evaluating|assessing|analyzing)\s+/i, '').trim();
      return clean.charAt(0).toLowerCase() + clean.slice(1);
    })
    .filter(p => {
      if (p.length < 5 || p.length > 40) return false;
      // Reject if it overlaps with the primary subject
      if (subject && normalize(subject).includes(normalize(p.split(' ')[0]))) return false;
      if (subject && normalize(p).includes(normalize(subject.split(' ')[0]))) return false;
      // Reject if it contains a conjunction chain ("X and Y and Z") — audit-report smell
      if ((p.match(/ and /g) || []).length >= 2) return false;
      // Reject if it's all-generic terminology
      if (isGenericSubject(p)) return false;
      return true;
    });

  // Use at most 1 additional phrase — no chaining
  if (additionalPhrases.length >= 1) {
    parts.push(`with focus on ${additionalPhrases[0]}`);
  } else if (workSubtype && workSubtype !== 'implementing') {
    // Mention the subtype action
    const subtypeDescriptions = {
      debugging:    'investigating and resolving issues',
      testing:      'writing and running tests',
      refactoring:  'restructuring and improving code quality',
      designing:    'creating and refining designs',
      researching:  'exploring solutions and best practices',
      reviewing:    'reviewing code and providing feedback',
      documenting:  'writing documentation and notes',
      planning:     'organizing tasks and priorities',
      deploying:    'shipping and releasing updates',
      integrating:  'connecting and configuring services',
    };
    if (subtypeDescriptions[workSubtype]) {
      parts.push(subtypeDescriptions[workSubtype]);
    }
  }

  // ── 3. Purpose clause — WHY the work was done (replaces "using X" tool list) ──
  // The intent type tells us the purpose of the session.
  // Generate a short outcome-oriented clause instead of listing apps.
  const intentKey   = workSubtype || primaryCategory;
  const INTENT_MAP  = {
    debugging: 'researching', testing: 'testing', refactoring: 'refactoring',
    implementing: 'implementing', designing: 'designing', researching: 'researching',
    reviewing: 'reviewing', deploying: 'deploying', planning: 'planning',
    documenting: 'documenting', integrating: 'implementing', architecting: 'planning',
    configuring: 'implementing', migrating: 'implementing',
  };
  const resolvedIntent = INTENT_MAP[intentKey] || (
    primaryCategory === 'development' ? 'implementing'
    : primaryCategory === 'design'    ? 'designing'
    : primaryCategory === 'research'  ? 'researching'
    : primaryCategory === 'planning'  ? 'planning'
    : 'implementing'
  );
  const intentDef = INTENT_TYPES[resolvedIntent];
  if (intentDef?.purpose && subject) {
    const purpose = intentDef.purpose(subject, project?.name);
    if (purpose && purpose.length >= 10 && !purpose.toLowerCase().includes('undefined')) {
      parts.push(purpose);
    }
  }

  // Assemble first sentence — hard cap at 2 clauses to prevent audit-report chaining.
  // Pattern: "[Verb] [subject][, secondary clause]."
  // The purpose clause (parts[2]) is dropped when a secondary phrase is already present.
  let firstSentence = '';
  const usePurpose = parts.length >= 3 && !parts[1].startsWith('with focus on');
  if (parts.length === 1) {
    firstSentence = parts[0] + '.';
  } else if (usePurpose) {
    // Use main action + purpose clause only (skip secondary phrase)
    firstSentence = `${parts[0]} ${parts[2]}.`;
  } else {
    // Use main action + secondary detail
    firstSentence = `${parts[0]}, ${parts[1]}.`;
  }

  // Capitalize and clean up
  firstSentence = firstSentence.charAt(0).toUpperCase() + firstSentence.slice(1);
  firstSentence = firstSentence.replace(/\s{2,}/g, ' ');

  // ── 4. Context note ──────────────────────────────────────────────────────
  const contextParts = [];

  if (durationMins >= 5) {
    const hrs = Math.floor(durationMins / 60);
    const mins = Math.round(durationMins % 60);
    const durLabel = hrs > 0
      ? mins > 0 ? `${hrs}h ${mins}m` : `${hrs}h`
      : `${mins}m`;

    if (isDeepWork && focusQuality === 'high' && durationMins >= 60) {
      contextParts.push(`Deep focus session — ${durLabel} uninterrupted`);
    } else if (focusQuality === 'high') {
      contextParts.push(`${durLabel} focused session`);
    } else if (focusQuality === 'low' && contextSwitches > 20) {
      contextParts.push(`${durLabel} with high context switching`);
    } else {
      contextParts.push(`${durLabel}`);
    }
  }

  if (client?.name) contextParts.push(`client: ${client.name}`);

  // Include AI tool note if significant portion of session was with AI
  if (aiTopics.length > 0) {
    const totalAISecs = aiTopics.reduce((s, t) => s + (t.durationSecs || 0), 0);
    const totalSecs = (durationMins || 0) * 60;
    if (totalSecs > 0 && totalAISecs / totalSecs >= 0.3) {
      contextParts.push('with AI assistance');
    }
  }

  const contextNote = contextParts.length
    ? contextParts.join(', ').replace(/^./, c => c.toUpperCase()) + '.'
    : '';

  const description = [firstSentence, contextNote]
    .filter(Boolean)
    .join(' ')
    .trim();

  // Confidence is higher when we have specific signals
  const hasSpecificSignal = windowTitlePhrases.length > 0 || aiTopics.length > 0;
  return { description, confidence: hasSpecificSignal ? 0.88 : 0.62 };
}

// ─── Main Writing Function (Presentation Layer) ───────────────────────────────
// eventWritingEngine no longer performs reasoning.
// It formats and assembles output from upstream engines.

export function writeEventContent(context, existing = {}) {
  const preserveTitle = hasMeaningfulTitle(existing.title);
  // Preserve description only if it's genuinely user-written (not an auto-generated template)
  const existingDesc = (existing.description || '').trim();
  const preserveDescription = existingDesc.length > 10 && !isAutoGeneratedDescription(existingDesc);

  const titleResult = preserveTitle
    ? { title: existing.title, confidence: 1.0, source: 'manual', alternates: [] }
    : generateTitle(context);

  const descResult = preserveDescription
    ? { description: existingDesc, confidence: 1.0 }
    : generateDescription(context, titleResult.title);

  // Final quality gate — flag outputs that failed validation so callers can
  // decide whether to prompt for manual correction.
  const qualityReport = (!preserveTitle || !preserveDescription)
    ? checkNarrativeQuality(titleResult.title, descResult.description, { project: context.project })
    : null;

  return {
    title:                    titleResult.title,
    titleConfidence:          titleResult.confidence,
    titleSource:              titleResult.source,
    titleAlternates:          titleResult.alternates,
    contextKey:               buildContextKey(context),
    description:              descResult.description,
    descConfidence:           descResult.confidence,
    category:                 context.primaryCategory,
    isDeepWork:               context.isDeepWork,
    titleWasGenerated:        !preserveTitle,
    descriptionWasGenerated:  !preserveDescription,
    isEditable:               true,
    qualityReport,
  };
}

/**
 * Orchestrator-powered writeEventContent.
 * Runs the full sanitize → rank → infer → humanize pipeline,
 * then packages output into the standard event content shape.
 *
 * @param {Array}  autoSessions
 * @param {Object} existing - { title, description }
 * @param {Object} project
 * @param {Object} client
 * @returns {Object} event content (synchronous)
 */
export function writeEventContentWithReasoning(autoSessions = [], existing = {}, project = null, client = null, sessionId = null) {
  try {
    const result = orchestrateSync(autoSessions, { project, client, existing, sessionId });
    return {
      title:                    result.title,
      titleConfidence:          result.qualityScore,
      titleSource:              result.titleSource,
      titleAlternates:          [],
      contextKey:               `${result.workMode}|${result.primaryCategory}|${result.topFeature?.featureId || 'none'}`,
      description:              result.description,
      descConfidence:           result.qualityScore,
      category:                 result.primaryCategory,
      isDeepWork:               result.isDeepWork,
      titleWasGenerated:        result.titleSource !== 'manual',
      descriptionWasGenerated:  result.descSource  !== 'manual',
      isEditable:               true,
      overallConfidence:        result.overallConfidence,
    };
  } catch {
    // Fall back to legacy context-based generation with full analyzed context
    const context = analyzeContext({ autoSessions, project, client });
    return writeEventContent(context, existing);
  }
}

// ─── Batch Processing ─────────────────────────────────────────────────────────

export function writeMissingEventContent(sessions, autoSessions = [], projects = [], clients = []) {
  const results = [];
  const nowSec = Date.now() / 1000;

  for (const session of sessions) {
    if (hasMeaningfulTitle(session.title)) continue;
    // Never generate AI titles for break sessions
    if (session.session_type === 'break') continue;

    const sStart = session.started_at
      ? (typeof session.started_at === 'number' ? session.started_at : new Date(session.started_at).getTime() / 1000)
      : 0;

    // Skip sessions that haven't started yet — scheduled future events
    // should only receive AI titles once they've been tracked
    if (sStart > nowSec) continue;
    const sEnd = session.ended_at
      ? (typeof session.ended_at === 'number' ? session.ended_at : new Date(session.ended_at).getTime() / 1000)
      : sStart + (session.duration_seconds || 0);

    const relevantAuto = autoSessions.filter(a => {
      const aStart = typeof a.started_at === 'number' ? a.started_at : new Date(a.started_at).getTime() / 1000;
      const aEnd   = typeof a.ended_at   === 'number' ? a.ended_at   : (aStart + (a.duration_seconds || 0));
      return aStart < sEnd && aEnd > sStart;
    });

    const project = projects.find(p => p.id === session.project_id) || null;
    const client  = clients.find(c  => c.id === session.client_id)  || null;

    // Route ALL missing-content generation through the full orchestration pipeline.
    // This ensures every event uses the 12-stage reasoning pipeline instead of
    // the legacy 4-stage writeEventContent path.
    const written = writeEventContentWithReasoning(
      relevantAuto,
      { title: session.title, description: session.notes || session.description },
      project,
      client,
      session.id,
    );

    results.push({ session, context: null, written });
  }

  return results;
}

// ─── Title Validation ─────────────────────────────────────────────────────────

const VAGUE_PATTERNS = [
  /^general$/i, /^work$/i, /^task$/i, /^untitled/i,
  /^session$/i, /^focus$/i, /^focus session$/i, /^focus block$/i,
  /^deep work$/i, /^new event$/i, /^scheduled work$/i,
  /^auto[- ]?tracked$/i, /^computer time$/i, /^tracked$/i,
  /^auto\s*:/i,
];

export function isVagueTitle(title = '') {
  const norm = normalize(title);
  return !norm || VAGUE_PATTERNS.some(p => p.test(norm)) || norm.length < 4;
}

export function improvVagueTitle(vagueTitle, context) {
  if (!isVagueTitle(vagueTitle)) return vagueTitle;
  return generateTitle(context).title;
}
