/**
 * Narrative Synthesis Engine — v2
 * Semantic narrative synthesis for workflow-aware productivity descriptions.
 *
 * v2 philosophy: semantic composition, not template generation.
 *
 * Instead of: verb + noun (from largest signal)
 * Now:        compound semantic phrase from fused workblock + ontology + signals
 *
 * Target quality: Rize.io / Linear AI — specific, behavioral, workflow-aware.
 * - No "Auto:" prefixes
 * - No app-name-as-title patterns
 * - No robotic repetitive structures
 * - No isolated telemetry descriptions
 * - Compound phrases from feature relationships
 * - Workflow-level understanding, not app-level
 */

import { WORKFLOW_ARCHETYPES, getIntentFeaturePhrase } from './productivityOntologyEngine.js';
import { INTENT_TYPES, inferDomain, inferCapability } from './intentInferenceEngine.js';
import { isAutoGeneratedDescription } from './sessionSummaryEngine.js';
import {
  isGenericSubject, filterGenericKeywords,
  scoreSubjectSpecificity, checkTitleRejectPatterns,
} from './genericKeywordFilter.js';
import { isTitleAcceptable } from './narrativeQualityEngine.js';

// ─── Utility / OS Apps ────────────────────────────────────────────────────────
// These apps are system tools — never meaningful work subjects or "tools used"
const UTILITY_APP_RE = /^(snipping\s*tool|snip\s*&\s*sketch|screenshot|photos|camera|calculator|notepad|wordpad|paint|paint\s*3d|windows\s*explorer|file\s*explorer|finder|activity\s*monitor|task\s*manager|system\s*preferences|settings|control\s*panel|system\s*info|disk\s*utility|magnifier|sticky\s*notes|clock|calendar\s*app|weather|maps|mail\s*app|news|microsoft\s*store|app\s*store|spotlight|cortana|siri|widgets|action\s*center)$/i;

function isUtilityApp(appName = '') {
  return UTILITY_APP_RE.test(appName.trim());
}

// ─── Vague Subject Guard ──────────────────────────────────────────────────────
// Subjects that read as generic / low-information
const VAGUE_SUBJECT_WORDS = new Set([
  'functions', 'things', 'stuff', 'items', 'content', 'data', 'information',
  'task', 'tasks', 'work', 'session', 'activity', 'feature', 'features',
  // App/route labels that must never become title subjects
  'productivity', 'dashboard', 'analytics', 'application', 'app',
  'platform', 'workspace', 'management', 'overview', 'summary',
  'settings', 'configuration', 'system', 'module', 'interface',
]);

function isVagueSubject(subject = '') {
  if (!subject || subject.length < 4) return true;
  const words = subject.toLowerCase().split(/\s+/);
  // All words are vague
  if (words.every(w => VAGUE_SUBJECT_WORDS.has(w))) return true;
  // Ends with a very generic word ("App Functions", "App Tasks")
  const lastWord = words[words.length - 1];
  if (VAGUE_SUBJECT_WORDS.has(lastWord) && words.length <= 3) return true;
  return false;
}

// ─── Title Phrase Bank ────────────────────────────────────────────────────────
// Varied, non-repetitive phrase structures — each used contextually.

const TITLE_STRUCTURES = {
  // verb + subject (most common)
  verb_subject: (verb, subject) => `${verb} ${subject}`,
  // subject + context
  subject_context: (subject, context) => `${subject} — ${context}`,
  // Gerund phrase
  gerund: (verb, subject) => `${verb} ${subject}`,
  // Noun phrase (no leading verb)
  noun_phrase: (subject) => subject,
};

// ─── Verb Selection by Mode ───────────────────────────────────────────────────

const MODE_VERB_SETS = {
  deep_implementation: ['Implementing', 'Building', 'Developing', 'Engineering', 'Creating', 'Constructing'],
  debugging:   ['Debugging', 'Fixing', 'Diagnosing', 'Resolving', 'Troubleshooting'],
  design_work: ['Designing', 'Crafting', 'Refining', 'Prototyping', 'Shaping', 'Wireframing'],
  research:    ['Analyzing', 'Evaluating', 'Exploring', 'Studying', 'Examining'],  // "Researching" removed — too generic
  planning:    ['Planning', 'Architecting', 'Scoping', 'Mapping out', 'Structuring', 'Designing'],
  refactoring: ['Refactoring', 'Improving', 'Optimizing', 'Restructuring', 'Cleaning up', 'Simplifying'],
  documenting: ['Documenting', 'Writing', 'Drafting', 'Composing', 'Authoring'],
  documentation: ['Documenting', 'Writing', 'Drafting', 'Composing', 'Authoring'],
  code_review: ['Reviewing', 'Auditing', 'Evaluating', 'Inspecting', 'Assessing'],
  testing:     ['Testing', 'Validating', 'Verifying', 'QA-ing', 'Writing tests for'],
};

// ─── Subject Extraction ───────────────────────────────────────────────────────

const LEADING_VERB_RE = /^(building|implementing|designing|creating|developing|fixing|debugging|testing|writing|researching|refactoring|reviewing|planning|improving|adding|updating|configuring|setting\s+up|working\s+on|exploring|optimizing|crafting|prototyping|engineering|deploying|drafting|validating|resolving)\s+/i;

function extractSubjectFromPhrase(phrase) {
  const match = phrase.match(LEADING_VERB_RE);
  if (match) {
    const obj = phrase.slice(match[0].length).trim();
    return { subject: capitalizeFirst(obj), verbExtracted: match[1] };
  }
  return { subject: capitalizeFirst(phrase), verbExtracted: null };
}

function capitalizeFirst(str = '') {
  return str ? str.charAt(0).toUpperCase() + str.slice(1) : '';
}

function capitalizeWords(str = '') {
  return str.replace(/\b([a-z])/g, c => c.toUpperCase());
}

function dedup(title = '') {
  const words = title.split(/\s+/);
  const result = [];
  for (let i = 0; i < words.length; i++) {
    if (i === 0 || words[i].toLowerCase() !== words[i - 1].toLowerCase()) {
      result.push(words[i]);
    }
  }
  return result.join(' ').replace(/(\b\w+\s+\w+\b)\s+\1/gi, '$1');
}

// ─── Verb Picking (per-call state, not module-level) ─────────────────────────
// NOTE: verb rotation state is passed in as a parameter to avoid module-level
// mutable state that would persist across users and sessions.

function pickVerb(workMode, position = 0, usedVerbs = []) {
  const verbs = MODE_VERB_SETS[workMode] || MODE_VERB_SETS.deep_implementation;

  for (let i = position; i < verbs.length + position; i++) {
    const verb = verbs[i % verbs.length];
    if (!usedVerbs.slice(-3).includes(verb)) {
      return verb;
    }
  }
  return verbs[position % verbs.length];
}

// ─── Semantic Compound Phrase Builders ───────────────────────────────────────
// Build compound phrases from feature combinations and workflow context.
// This is the key upgrade: instead of "verb + topSignal", we synthesize
// meaning from the RELATIONSHIP between signals.

const CONNECTING_PHRASES = [
  'and refining',
  'alongside',
  'while iterating on',
  'with focus on',
  'and improving',
  'and optimizing',
];

function buildCompoundSubject(reasoning) {
  const { featureGraph, compressed, fusedWorkblock, intentResult, workMode, project } = reasoning;
  const intentType = intentResult?.type || workMode?.replace('deep_', '') || 'implementing';

  // Priority 1: AI conversation topic — most precise signal available
  // (e.g. "Fix burnout calculation — Claude" → subject = "Burnout Calculation Fix")
  const aiTopics = compressed?.aiConversationTopics || [];
  if (aiTopics.length > 0 && aiTopics[0].topic?.length >= 6) {
    const { subject } = extractSubjectFromPhrase(aiTopics[0].topic);
    if (!isVagueSubject(subject) && !isProjectNameOnly(subject, project)) {
      return { subject: capitalizeFirst(subject), source: 'ai_topic', confidence: 0.94 };
    }
  }

  // Priority 1b: Dominant workflow label — the workflow that contributed the most
  // time in the session, filtered by the workflowDominanceEngine. Use it when the
  // dominance score is high and it adds specificity beyond the project name alone.
  const dominantLabel = compressed?.dominantWorkflowLabel;
  const dominanceScore = compressed?.dominanceScore || 0;
  if (dominantLabel && dominantLabel.length >= 8 && dominanceScore >= 0.65
      && !isProjectNameOnly(dominantLabel, project)) {
    const { subject } = extractSubjectFromPhrase(dominantLabel);
    if (!isVagueSubject(subject)) {
      return { subject: capitalizeFirst(subject), source: 'dominant_workflow', confidence: Math.min(dominanceScore + 0.1, 0.92) };
    }
  }

  // Priority 2: fusedWorkblock provides synthesized multi-signal context
  if (fusedWorkblock?.fusedSubject && fusedWorkblock.fusedSubject.length >= 8
      && !isProjectNameOnly(fusedWorkblock.fusedSubject, project)) {
    return { subject: fusedWorkblock.fusedSubject, source: 'fusion', confidence: fusedWorkblock.fusionConfidence };
  }

  // Priority 3: best window title phrase — actual work description
  for (const p of compressed?.titlePhrases || []) {
    if (p.isAITopic) continue; // already handled above
    const { subject } = extractSubjectFromPhrase(p.phrase);
    if (subject.length >= 8 && !isVagueSubject(subject) && !isGenericSubject(subject)
        && !isUtilityApp(subject) && !isProjectNameOnly(subject, project)) {
      return { subject: capitalizeFirst(subject), source: 'title_phrase', confidence: 0.85 };
    }
  }

  // Priority 4: feature compound from fusion (two features = specific objective)
  if (fusedWorkblock?.featureCompound) {
    return { subject: fusedWorkblock.featureCompound, source: 'feature_compound', confidence: 0.80 };
  }

  // Priority 5: intent-feature phrase from ontology (Flow Ledger-specific fallback)
  const topFeatureId = featureGraph?.activeCluster?.[0]?.featureId;
  if (topFeatureId) {
    const ontologyPhrase = getIntentFeaturePhrase(intentType, topFeatureId);
    if (ontologyPhrase) {
      return { subject: ontologyPhrase, source: 'ontology_phrase', confidence: 0.72 };
    }
  }

  // Priority 6: keyword-synthesized subject (better than just the feature label)
  const synth = synthesizeSubjectFromKeywords(compressed, intentType, project);
  if (synth) return { subject: synth, source: 'keyword_synthesis', confidence: 0.65 };

  // Priority 7: top feature label
  if (featureGraph?.topFeature?.label) {
    return { subject: featureGraph.topFeature.label, source: 'feature_label', confidence: 0.60 };
  }

  // Priority 8: primary intent phrase
  if (reasoning.primaryIntent?.length >= 10) {
    return { subject: capitalizeFirst(reasoning.primaryIntent), source: 'intent', confidence: 0.50 };
  }

  return { subject: null, source: 'none', confidence: 0 };
}

// Returns true when a subject is JUST the project name (provides no extra specificity)
function isProjectNameOnly(subject, project) {
  if (!project?.name || !subject) return false;
  const subNorm = subject.toLowerCase().trim();
  const projNorm = project.name.toLowerCase().trim();
  return subNorm === projNorm || subNorm === projNorm + ' development' || subNorm === projNorm + ' features';
}

// Synthesize a semantic subject phrase from keywords when no phrase is available.
// Uses the generic keyword filter to ensure only meaningful words are used.
function synthesizeSubjectFromKeywords(compressed, intentType, project) {
  const rawKeywords = compressed?.keywords || [];
  const category = compressed?.primaryCategory || 'development';

  // Hard skip list (browser/AI tool names that pollute keywords)
  const HARD_SKIP = new Set([
    'using', 'from', 'with', 'into', 'that', 'this', 'have', 'been', 'will',
    'chrome', 'safari', 'firefox', 'edge', 'claude', 'chatgpt', 'gemini',
    'code', 'vscode', 'cursor', 'copilot',
  ]);

  // Step 1: Remove hard skips
  const afterHardSkip = rawKeywords.filter(k => !HARD_SKIP.has(k) && k.length >= 4);

  // Step 2: Remove ALL generic application terms
  // This is the critical fix: "productivity", "dashboard", "analytics", "system",
  // "module", "feature", "component", "interface" etc. are EXCLUDED here.
  const meaningful = filterGenericKeywords(afterHardSkip, { strict: false })
    .filter(k => k.length >= 5)
    .slice(0, 4);

  if (meaningful.length >= 2) {
    // Build compound phrase from top 2 non-generic keywords
    const first  = capitalizeWords(meaningful[0]);
    const second = capitalizeWords(meaningful[1]);
    const candidate = `${first} and ${second}`;
    // Verify the compound is actually specific
    if (!isGenericSubject(candidate)) return candidate;
  }

  if (meaningful.length === 1) {
    const suffix = {
      development: 'Implementation',
      design:      'Design',
      research:    'Analysis',
      planning:    'Architecture',
      writing:     'Documentation',
    }[category] || 'Development';
    const candidate = capitalizeWords(`${meaningful[0]} ${suffix}`);
    if (!isGenericSubject(candidate)) return candidate;
  }

  return null;
}

// ─── Outcome-Driven Description Builder ──────────────────────────────────────
// Builds descriptions that answer: WHAT was done + WHY + WHAT outcome was pursued.
// Apps are NEVER listed — the focus is entirely on workflow, intent, and purpose.

function buildOutcomeNarrative(reasoning, titleSubject) {
  const {
    compressed, intentResult, continuityProfile, workMode, project,
    fusedWorkblock,
  } = reasoning;

  const intentType = intentResult?.type || workMode?.replace('deep_', '') || 'implementing';
  const intentDef  = INTENT_TYPES[intentType] || INTENT_TYPES.implementing;

  // ── Past verb — chosen by intent, not by app ───────────────────────────────
  const pastVerb = intentDef.pastVerbs[0];

  // ── Primary subject — specific work description ───────────────────────────
  // Prefer: AI topic > fused subject > window title phrase > fallback
  let subject = titleSubject || null;

  // Enrich the subject if it's too short or is just the project name
  if (!subject || subject.length < 5 || isProjectNameOnly(subject, project)) {
    const aiTopics = compressed?.aiConversationTopics || [];
    if (aiTopics.length > 0 && aiTopics[0].topic?.length >= 6) {
      const { subject: aiSubj } = extractSubjectFromPhrase(aiTopics[0].topic);
      if (!isVagueSubject(aiSubj)) subject = capitalizeFirst(aiSubj);
    }
  }

  if (!subject || isVagueSubject(subject) || isGenericSubject(subject)) {
    for (const p of compressed?.titlePhrases || []) {
      const { subject: ps } = extractSubjectFromPhrase(p.phrase);
      if (ps.length >= 6 && !isVagueSubject(ps) && !isGenericSubject(ps) && !isProjectNameOnly(ps, project)) {
        subject = capitalizeFirst(ps);
        break;
      }
    }
  }

  // Expand the subject with secondary phrase context when available
  const secondPhrase = getSecondaryPhrase(compressed, subject);

  // ── Purpose clause — explains WHY the work was done ───────────────────────
  const purposeClause = intentDef.purpose
    ? intentDef.purpose(subject, project?.name)
    : null;

  // ── Continuity clause — situates the work in ongoing context ──────────────
  let continuityClause = null;
  if (continuityProfile?.isContinuingWork) {
    const obj = continuityProfile?.activeObjective?.description;
    continuityClause = obj
      ? `as part of ongoing work on ${obj}`
      : 'as part of ongoing implementation';
  }

  // ── Assemble the sentence ──────────────────────────────────────────────────
  // Pattern: "[PastVerb] [subject][, expanding into secondPhrase], [purpose clause]."
  // Never list apps. Always lead with what was done and why.

  const subjectStr = subject
    ? (subject.charAt(0).toLowerCase() + subject.slice(1))
    : (project?.name ? project.name.toLowerCase() : 'the work');

  let body = `${pastVerb} ${subjectStr}`;

  // Add secondary context when it genuinely extends the primary (no overlap)
  if (secondPhrase) {
    const bodyNorm = body.toLowerCase();
    const secNorm  = secondPhrase.toLowerCase();
    const hasOverlap = secNorm.split(' ').some(w => w.length >= 5 && bodyNorm.includes(w));
    if (!hasOverlap) {
      body = `${body}, including ${secNorm}`;
    }
  }

  // Append purpose clause
  if (purposeClause) {
    body = `${body} ${purposeClause}`;
  }

  // Append continuity clause
  if (continuityClause) {
    body = `${body} — ${continuityClause}`;
  }

  return capitalizeFirst(body) + '.';
}

// Returns a secondary phrase from the second distinct title phrase (for description enrichment)
function getSecondaryPhrase(compressed, primarySubject) {
  const BROWSER_RE  = /^(chrome|firefox|safari|arc|brave|edge|opera)$/i;
  const AI_APP_RE   = /^(claude|chatgpt|gemini|copilot|perplexity|poe|phind)/i;
  const primaryNorm = (primarySubject || '').toLowerCase();

  for (const p of (compressed?.titlePhrases || []).slice(1, 5)) {
    if (p.isAITopic) continue;
    const { subject } = extractSubjectFromPhrase(p.phrase);
    const subNorm = subject.toLowerCase();
    if (
      subNorm.length >= 6 &&
      !isVagueSubject(subNorm) &&
      !isGenericSubject(subNorm) &&
      !BROWSER_RE.test(subNorm) &&
      !AI_APP_RE.test(subNorm) &&
      !isUtilityApp(subNorm) &&
      !primaryNorm.includes(subNorm.split(' ')[0]) &&
      !subNorm.includes(primaryNorm.split(' ')[0])
    ) {
      return capitalizeFirst(subject);
    }
  }
  return null;
}

// ─── Legacy alias kept for compatibility ─────────────────────────────────────
function buildDescriptionClauses(reasoning, titleSubject) {
  // Redirect to the new outcome-driven builder — returns a single assembled string
  // wrapped in an array so callers that iterate over clauses still work.
  return [buildOutcomeNarrative(reasoning, titleSubject)];
}

// ─── Title Generation ─────────────────────────────────────────────────────────

/**
 * Synthesize a high-quality, semantically compound title.
 * v2: Uses fusedWorkblock + ontology phrases first, falls back gracefully.
 */
function synthesizeTitle(reasoning, position = 0) {
  const { workMode, primaryCategory, project, intentResult } = reasoning;

  // Pick verb from the intent type for consistency — intentResult verb is more
  // specific than the generic workMode-based verb.
  const intentType = intentResult?.type || workMode?.replace('deep_', '') || 'implementing';
  const intentDef  = INTENT_TYPES[intentType] || INTENT_TYPES.implementing;
  const verbs      = intentDef.verbs || MODE_VERB_SETS[workMode] || MODE_VERB_SETS.deep_implementation;
  const usedVerbs  = reasoning._usedVerbs || [];
  const verb       = verbs[position % verbs.length] || pickVerb(workMode, position, usedVerbs);

  // Build compound subject from all available semantic sources
  const { subject, source, confidence } = buildCompoundSubject(reasoning);

  // ── Continuity shortcut — use "Continuing X" when session strongly continues ─
  if (reasoning.continuityProfile?.isContinuingWork &&
      reasoning.continuityProfile?.continuationTitleHint &&
      reasoning.continuityProfile.continuityConfidence >= 0.65) {
    const hint = reasoning.continuityProfile.continuationTitleHint;
    if (hint && isTitleAcceptable(hint)) return hint.slice(0, 72);
  }

  if (subject && confidence >= 0.5) {
    // Guard: reject all-generic subjects before building any title
    if (isGenericSubject(subject)) {
      // Fall through to graceful fallback below
    } else {
      // Already starts with a gerund verb? Use as-is to avoid double verbs.
      if (/^(implementing|building|designing|developing|engineering|debugging|researching|refactoring|reviewing|documenting|testing|planning|exploring|crafting|optimizing|analyzing)/i.test(subject)) {
        const candidate = dedup(capitalizeFirst(subject)).slice(0, 72);
        if (isTitleAcceptable(candidate)) return candidate;
      }

      // NEVER blindly prepend project name — only do it when subject is very short
      // and generic (≤2 meaningful words, no proper nouns from Title Case).
      const hasProperNounContent = (subject.match(/[A-Z][a-z]/g) || []).length >= 2;
      const wordCount = subject.split(/\s+/).length;
      const isShortGeneric = wordCount <= 2 && !hasProperNounContent && source !== 'ai_topic';

      let candidate;
      if (project?.name && isShortGeneric && !subject.toLowerCase().includes(project.name.toLowerCase())) {
        candidate = dedup(`${verb} ${project.name} ${subject}`).slice(0, 72);
      } else {
        candidate = dedup(`${verb} ${subject}`).slice(0, 72);
      }

      // Quality gate: only return if not auto-rejected
      const { rejected } = checkTitleRejectPatterns(candidate);
      if (!rejected) return candidate;
    }
  }

  // Graceful fallbacks — produce semantic titles, not just project names
  if (project?.name) {
    const domainHint = inferTitleDomainFallback(reasoning);
    return domainHint
      ? dedup(`${verb} ${domainHint}`).slice(0, 72)
      : dedup(`${verb} ${project.name}`).slice(0, 72);
  }

  const categoryLabels = {
    development: 'Feature Development',
    design:      'UI Design System',
    writing:     'Technical Documentation',
    research:    'Technical Research',
    planning:    'Architecture Planning',
    meeting:     'Team Sync',
  };
  return `${verb} ${categoryLabels[primaryCategory] || 'Product Development'}`;
}

// When no good subject is found, infer a semantic domain label from keywords
function inferTitleDomainFallback(reasoning) {
  const keywords   = reasoning.compressed?.keywords || [];
  const intentType = reasoning.intentResult?.type || 'implementing';
  const category   = reasoning.primaryCategory || 'development';

  const DOMAIN_ELEVATIONS = {
    burnout: 'Burnout Risk Intelligence',     fatigue: 'Fatigue Detection Systems',
    calendar: 'Calendar Intelligence',        scheduling: 'Scheduling Intelligence',
    analytics: 'Analytics Pipeline',          insight: 'Productivity Insights',
    session: 'Session Intelligence',          tracking: 'Activity Tracking',
    'ai': 'AI Intelligence Systems',         reasoning: 'Contextual Reasoning',
    semantic: 'Semantic Intelligence',        narrative: 'Narrative Synthesis',
    workflow: 'Workflow Intelligence',        continuity: 'Continuity Intelligence',
    design: 'Design System',                  component: 'UI Component Architecture',
    performance: 'Performance Optimization', database: 'Data Layer',
    authentication: 'Authentication System', notification: 'Notification System',
    report: 'Reporting Pipeline',
  };

  for (const kw of keywords) {
    for (const [term, elevation] of Object.entries(DOMAIN_ELEVATIONS)) {
      if (kw.toLowerCase().includes(term)) return elevation;
    }
  }
  return null;
}

// ─── Description Generation ───────────────────────────────────────────────────

const DESC_OPENING_VERBS = {
  deep_implementation: ['Implemented', 'Built', 'Developed', 'Worked on'],
  debugging: ['Debugged', 'Fixed', 'Resolved', 'Investigated'],
  design_work: ['Designed', 'Crafted', 'Refined', 'Prototyped'],
  research: ['Researched', 'Explored', 'Investigated', 'Analyzed'],
  planning: ['Planned', 'Architected', 'Scoped', 'Mapped out'],
  refactoring: ['Refactored', 'Optimized', 'Improved', 'Restructured'],
  documenting: ['Documented', 'Wrote', 'Drafted'],
  documentation: ['Documented', 'Wrote', 'Drafted'],
  code_review: ['Reviewed', 'Audited', 'Evaluated'],
  testing: ['Tested', 'Validated', 'Verified'],
};

function buildDescriptionParts(reasoning, generatedTitle) {
  // v2: delegate to semantic clause builder for richer compound descriptions
  const subject = generatedTitle
    ? generatedTitle
        .replace(/^(Implementing|Building|Developing|Engineering|Creating|Debugging|Fixing|Troubleshooting|Resolving|Designing|Crafting|Prototyping|Researching|Exploring|Analyzing|Planning|Architecting|Scoping|Refactoring|Optimizing|Improving|Documenting|Writing|Drafting|Testing|Validating|Reviewing|Auditing)\s+/i, '')
        .trim()
    : null;

  return buildDescriptionClauses(reasoning, subject || reasoning.project?.name || null);
}

function buildContextNote(reasoning) {
  const { behaviorProfile, compressed, client, sessionDurationMins } = reasoning;
  const { isDeepWork, productivityState } = behaviorProfile || {};

  // Prefer the actual session duration (passed from generateSessionRecap).
  // Fall back to compressed active time only if session duration isn't provided.
  const durationMins = sessionDurationMins || compressed?.totalActiveMins || 0;

  let note = '';

  if (isDeepWork && durationMins >= 60) {
    note = `Deep focus — ${Math.round(durationMins)} min of uninterrupted work.`;
  } else if (productivityState === 'exploratory' && durationMins >= 20) {
    note = `${Math.round(durationMins)}-min research and exploration session.`;
  } else if (durationMins >= 15) {
    note = `${Math.round(durationMins)}-min session.`;
  }

  if (client?.name) {
    note = note ? `${note} Client: ${client.name}.` : `Client: ${client.name}.`;
  }

  return note;
}

function synthesizeDescription(reasoning, generatedTitle) {
  // Extract title subject (strip leading verb)
  const titleSubject = generatedTitle
    ? generatedTitle
        .replace(/^(Implementing|Building|Developing|Engineering|Creating|Constructing|Debugging|Fixing|Resolving|Troubleshooting|Diagnosing|Investigating|Analyzing|Exploring|Evaluating|Designing|Crafting|Refining|Prototyping|Wireframing|Planning|Architecting|Scoping|Mapping\s+out|Structuring|Refactoring|Optimizing|Improving|Restructuring|Documenting|Writing|Drafting|Authoring|Testing|Validating|Verifying|Deploying|Releasing|Shipping|Reviewing|Auditing|Inspecting)\s+/i, '')
        .trim()
    : null;

  // Build the outcome narrative (replaces the old clause-list approach)
  const narrative = buildOutcomeNarrative(reasoning, titleSubject);

  // Append session context note
  const contextNote = buildContextNote(reasoning);
  const description = [narrative, contextNote].filter(Boolean).join(' ').trim();

  return { description, confidence: reasoning.overallConfidence || 0.75 };
}

// ─── Productivity Note Synthesis ──────────────────────────────────────────────

function synthesizeProductivityNote(reasoning) {
  const { behaviorProfile, compressed, workflowState } = reasoning;
  const { isDeepWork, isSustainedWork, productivityState, workMode, flowState } = behaviorProfile || {};
  const durationMins = compressed?.totalActiveMins || 0;
  const contextSwitches = compressed?.contextSwitches || 0;

  const dur = Math.round(durationMins);
  const activityLabel = workflowState?.activitySummary || 'focused work';

  if (isDeepWork && dur >= 90) {
    return `Deep focus — ${dur} min of sustained ${activityLabel} with minimal interruptions.`;
  }
  if (isDeepWork && dur >= 60) {
    return `Strong focus session — ${dur} min of ${activityLabel}.`;
  }
  if (isSustainedWork) {
    return `Productive ${dur}-min session of ${activityLabel}.`;
  }
  if (productivityState === 'exploratory') {
    return `Exploratory ${dur}-min session — research and investigation with ${contextSwitches} context switches.`;
  }
  if (contextSwitches > 25) {
    return `Fragmented ${dur}-min session (${contextSwitches} switches) — consider batching similar tasks.`;
  }
  return `${dur}-min ${activityLabel} session.`;
}

// ─── Alternate Title Generation ───────────────────────────────────────────────

function generateAlternateTitles(reasoning, primaryTitle) {
  const alts = [];
  const { project } = reasoning;

  // Alternate 1: different verb, same subject
  const alt1 = synthesizeTitle(reasoning, 1);
  if (alt1 && alt1 !== primaryTitle && isQualityTitle(alt1, project)) {
    alts.push(alt1);
  }

  // Alternate 2: feature-based title (only when feature is specific enough)
  const topFeature = reasoning.featureGraph?.topFeature;
  if (topFeature?.label && topFeature.label.length >= 8) {
    const intentDef = INTENT_TYPES[reasoning.intentResult?.type || 'implementing'];
    const verb2 = (intentDef?.verbs || [])[2] || pickVerb(reasoning.workMode, 2);
    const featTitle = dedup(`${verb2} ${topFeature.label}`).slice(0, 68);
    if (featTitle !== primaryTitle && isQualityTitle(featTitle, project)) {
      alts.push(featTitle);
    }
  }

  // Alternate 3: domain-elevated title (avoid bare "verb + project name")
  if (alts.length < 2) {
    const domainHint = inferTitleDomainFallback(reasoning);
    if (domainHint) {
      const intentDef = INTENT_TYPES[reasoning.intentResult?.type || 'implementing'];
      const verb3 = (intentDef?.verbs || [])[3] || pickVerb(reasoning.workMode, 3);
      const domainTitle = dedup(`${verb3} ${domainHint}`).slice(0, 68);
      if (domainTitle !== primaryTitle && !alts.includes(domainTitle) && isQualityTitle(domainTitle, project)) {
        alts.push(domainTitle);
      }
    }
  }

  return alts.slice(0, 2);
}

// ─── Quality Guards ───────────────────────────────────────────────────────────

const VAGUE_PATTERNS = [
  /^auto\s*:/i,
  /^general$/i,
  /^work$/i,
  /^task$/i,
  /^untitled/i,
  /^session$/i,
  /^focus$/i,
  /^focus session$/i,
  /^new event$/i,
  /^scheduled work$/i,
  /^tracked$/i,
  // Single-word "Verb ProjectName" combos that carry no specificity
  /^(investigating|researching|exploring|building|developing|implementing)\s+[a-z\s]{3,20}$/i,
];

// Additional check: titles that are just "Verb <project name>" add no specificity.
// Detect them by checking if the title is exactly 2 words where word1 is a vague
// gerund and word2 is a known project/company name pattern.
const VAGUE_GERUNDS = new Set([
  'investigating', 'researching', 'exploring', 'reviewing',
]);

function isVagueTwoWordTitle(title = '', project = null) {
  const words = title.trim().split(/\s+/);
  if (words.length !== 2) return false;
  const gerund = words[0].toLowerCase();
  if (!VAGUE_GERUNDS.has(gerund)) return false;
  // If the second word is the project name, it's a vague title
  if (project?.name && words[1].toLowerCase() === project.name.toLowerCase()) return true;
  return false;
}

function isQualityTitle(title = '', project = null) {
  if (!title || title.length < 6) return false;
  if (VAGUE_PATTERNS.some(p => p.test(title.trim()))) return false;
  if (/^(claude|chatgpt|vscode|figma|chrome|auto)\s*:?$/i.test(title.trim())) return false;
  if (isVagueTwoWordTitle(title, project)) return false;
  // ── Generic subject guard ──────────────────────────────────────────────────
  if (checkTitleRejectPatterns(title).rejected) return false;
  return true;
}

// ─── Main Synthesis Function ──────────────────────────────────────────────────

/**
 * Synthesize a complete set of narrative content from contextual reasoning output.
 *
 * @param {Object} reasoning - output of contextualReasoningEngine.reason()
 * @param {Object} [existing] - { title, description } — preserved if meaningful
 * @returns {Object} synthesizedContent
 */
export function synthesize(reasoning, existing = {}) {
  const preserveTitle = hasMeaningfulExistingTitle(existing.title);
  // Only preserve descriptions that are genuinely user-written — auto-generated
  // templates get replaced with the improved outcome-driven narrative.
  const existingDesc = (existing.description || '').trim();
  const preserveDesc = existingDesc.length > 10 && !isAutoGeneratedDescription(existingDesc);

  // Title
  const titleResult = (() => {
    if (preserveTitle) {
      return { title: existing.title, confidence: 1.0, source: 'manual', alternates: [] };
    }

    const title = synthesizeTitle(reasoning, 0);
    if (!isQualityTitle(title)) {
      // Emergency fallback
      const fallback = buildFallbackTitle(reasoning);
      return { title: fallback, confidence: 0.40, source: 'fallback', alternates: [] };
    }

    const alternates = generateAlternateTitles(reasoning, title);
    const source = reasoning.compressed?.titlePhrases?.length ? 'contextual_phrase'
      : reasoning.topFeature ? 'feature_graph'
      : reasoning.primaryIntent ? 'intent_inference'
      : 'mode_fallback';

    return {
      title,
      confidence: Math.round(reasoning.overallConfidence * 100) / 100,
      source,
      alternates,
    };
  })();

  // Description
  const descResult = preserveDesc
    ? { description: existing.description, confidence: 1.0 }
    : synthesizeDescription(reasoning, titleResult.title);

  // Productivity note
  const productivityNote = synthesizeProductivityNote(reasoning);

  // Deep work label
  const deepWorkLabel = buildDeepWorkLabel(reasoning);

  return {
    title: titleResult.title,
    titleConfidence: titleResult.confidence,
    titleSource: titleResult.source,
    titleAlternates: titleResult.alternates,
    description: descResult.description,
    descriptionConfidence: descResult.confidence,
    productivityNote,
    deepWorkLabel,
    category: reasoning.primaryCategory,
    isDeepWork: reasoning.isDeepWork,
    workMode: reasoning.workMode,
    titleWasGenerated: !preserveTitle,
    descriptionWasGenerated: !preserveDesc,
    isEditable: true,
  };
}

function hasMeaningfulExistingTitle(title = '', project = null) {
  if (!title || title.length <= 2) return false;
  if (VAGUE_PATTERNS.some(p => p.test(title.trim()))) return false;
  if (isVagueTwoWordTitle(title, project)) return false;
  // Reject bare app-name titles
  if (/^(claude|chatgpt|vscode|figma|chrome|auto|notion|linear|slack)\s*:?$/i.test(title.trim())) return false;
  return true;
}

function buildFallbackTitle(reasoning) {
  const { workMode, primaryCategory, project, intentResult } = reasoning;
  const intentType = intentResult?.type || workMode?.replace('deep_', '') || 'implementing';
  const intentDef  = INTENT_TYPES[intentType] || INTENT_TYPES.implementing;
  const verb       = (intentDef.verbs || [])[0] || pickVerb(workMode, 0);

  // Attempt domain elevation from keywords first — better than just project name
  const domainHint = inferTitleDomainFallback(reasoning);
  if (domainHint) return `${verb} ${domainHint}`;

  // Keyword-synthesized subject as next best option
  const synthSubject = synthesizeSubjectFromKeywords(reasoning.compressed, intentType, project);
  if (synthSubject) return `${verb} ${synthSubject}`;

  // Category-based semantic labels — more descriptive than "Research Session"
  const catLabels = {
    development: 'Feature Implementation',
    design:      'UI Design System',
    writing:     'Technical Documentation',
    research:    'Technical Analysis',
    planning:    'Architecture Planning',
    meeting:     'Team Alignment',
  };
  return `${verb} ${catLabels[primaryCategory] || 'Product Development'}`;
}

function buildDeepWorkLabel(reasoning) {
  const { isDeepWork, behaviorProfile, compressed } = reasoning;
  const durationMins = compressed?.totalActiveMins || 0;
  const contextSwitches = compressed?.contextSwitches || 0;

  if (durationMins >= 90 && contextSwitches < 5) return 'Deep Focus';
  if (durationMins >= 60 && contextSwitches < 10) return 'Focused Work';
  if (isDeepWork) return 'Deep Work';
  if (durationMins >= 30) return 'Work Session';
  return 'Quick Session';
}

/**
 * Batch synthesize for sessions without titles.
 *
 * @param {Array} reasoningResults - array of reason() outputs
 * @param {Array} existingData - array of { title, description } per session
 */
export function synthesizeBatch(reasoningResults = [], existingData = []) {
  return reasoningResults.map((reasoning, i) =>
    synthesize(reasoning, existingData[i] || {})
  );
}
