/**
 * Narrative QA Engine
 *
 * Automated quality gate for all generated titles and descriptions.
 * Called as the final step in the narrative pipeline before output is returned.
 *
 * Validates:
 *   1. Subject specificity — is the subject concrete and non-generic?
 *   2. Genericity — does the output contain blocked generic phrases?
 *   3. Attribution accuracy — does the subject match the actual activity?
 *   4. Human readability — does it read naturally without clause stacking?
 *   5. Repetition — is it repeating the same words the title uses?
 *   6. Workflow correctness — does the intent match the behavioral signal?
 *   7. Length and structure — is it appropriately concise?
 *
 * Each check returns a named finding with severity:
 *   FAIL  — reject the output, trigger fallback
 *   WARN  — allow with note; surface to caller
 *   PASS  — no issue found
 *
 * Usage:
 *   const report = validateNarrative({ title, description }, ownership, options);
 *   if (!report.passes) { ... use fallback ... }
 */

import { isGenericSubject, scoreSubjectSpecificity } from './genericKeywordFilter.js';

// ─── Blocked Patterns ─────────────────────────────────────────────────────────

// Title phrases that are definitively useless
const BLOCKED_TITLE_PATTERNS = [
  /^productivity\b/i,
  /^analytics\b/i,
  /^dashboard\b/i,
  /^system\b/i,
  /^module\b/i,
  /^feature development\b/i,
  /^project development\b/i,
  /\bproductivity analytics\b/i,
  /\bdashboard analytics\b/i,
  /\bfeature module\b/i,
  /^(inspecting|building|reviewing)\s+(productivity|analytics|dashboard|feature|system)\b/i,
  /^worked on\b/i,
  /^spent time\b/i,
  /^this involved\b/i,
  /^to advance\b/i,
  /^general\b/i,
  /^miscellaneous\b/i,
];

// Description opener phrases that mark template-generated output
const BLOCKED_DESC_OPENERS = [
  /^worked on\b/i,
  /^spent time (on|working)\b/i,
  /^this session involved\b/i,
  /^this work involved\b/i,
  /^to advance\b/i,
  /^in this session\b/i,
  /^during this session\b/i,
  /^this involved\b/i,
];

// Clauses stacked with connectors that make descriptions robotic
const CLAUSE_STACKING_RE = /,\s+(implementing|building|creating|developing|working on|resolving|fixing|setting up|integrating|refactoring|debugging|reviewing|testing)\b/gi;

// Title patterns that signal robotic output
const ROBOTIC_TITLE_RE = [
  /^Continuing\s+\w+\s+(Intelligence|Implementation|Development|System|Module|Feature)\b/i,
  /^(?:Implementing|Building|Developing)\s+(?:AI|ML|System|Feature|Module|Dashboard)\s+(?:Intelligence|System|Module|Feature|Development|Implementation)\b/i,
  /^Feature Development$/i,
  /^UI Design Work$/i,
  /^Development Session$/i,
  /^Coding Session$/i,
  /^Work Session$/i,
];

// Description patterns that signal low-intelligence auto-generation
const GENERIC_DESC_PATTERNS = [
  /used (a combination of|multiple|various) (tools|applications|approaches)/i,
  /session involved (a mix of|multiple|various)/i,
  /worked across (multiple|various|several) (tools|applications|workflows)/i,
  /combination of (development|coding|work|implementation) (activities|tasks|workflows)/i,
];

// ─── Shared Auto-Generated Detection ─────────────────────────────────────────
// Single canonical implementation used by BOTH reasoningOrchestrator.isManuallyWrittenDesc()
// and sessionSummaryEngine.isAutoGeneratedDescription(). Previously these were two
// separate implementations that gave different answers for the same input (R-05 / L-02).

const AUTO_GENERATED_PATTERNS = [
  // Legacy engine output signatures
  /Duration:\s*\d+\s*min/i,
  // "Worked on Auto:" / "Researched Auto:" / bare "Auto:" prefix
  /^(Worked on Auto:|Researched Auto:|Auto:)/i,
  // Generic subject auto-fill patterns
  /^Worked on\s+(the\s+)?(system|module|feature|dashboard|productivity|analytics)\b/i,
  // Old purpose-clause signatures
  /\b(using a combination of|using multiple|session involved a mix)\b/i,
  // Template-filler placeholders that no human writes
  /\b(App Functions|development and engineering work|design and UX work|writing and documentation|research and exploration|planning and organization|Completed focused work)\b/i,
  // Bureaucratic auto-gen output from old purpose() functions
  /\bensure\b.{3,40}\bconsistency and correctness\b/i,
  /analytics and productivity insights/i,
];

/**
 * Returns true if the description was definitively auto-generated by a previous
 * version of the engine and is therefore safe to regenerate.
 *
 * IMPORTANT: Do NOT catch "Built|Implemented|Developed|Designed" etc. — those are
 * valid user-written descriptions. Only catch patterns that only the engine produces.
 *
 * Exported so both reasoningOrchestrator and sessionSummaryEngine use the same logic.
 */
export function isAutoGeneratedContent(desc = '') {
  if (!desc || desc.trim().length < 5) return true;
  const d = desc.trim();
  return AUTO_GENERATED_PATTERNS.some(re => re.test(d));
}

// ─── Severity Levels ──────────────────────────────────────────────────────────

const SEVERITY = {
  FAIL: 'FAIL',
  WARN: 'WARN',
  PASS: 'PASS',
};

function finding(name, severity, message, details = {}) {
  return { name, severity, message, ...details };
}

// ─── Individual Checks ────────────────────────────────────────────────────────

function checkTitleGenericity(title = '') {
  if (!title) return finding('title_empty', SEVERITY.FAIL, 'Title is empty or missing');

  for (const pattern of BLOCKED_TITLE_PATTERNS) {
    if (pattern.test(title.trim())) {
      return finding('title_generic', SEVERITY.FAIL,
        `Title matches blocked generic pattern: "${pattern.toString()}"`, { title });
    }
  }

  for (const pattern of ROBOTIC_TITLE_RE) {
    if (pattern.test(title.trim())) {
      return finding('title_robotic', SEVERITY.FAIL,
        `Title matches robotic pattern: "${title}"`, { title });
    }
  }

  return finding('title_genericity', SEVERITY.PASS, 'Title is not generic');
}

function checkTitleSpecificity(title = '') {
  if (!title) return finding('title_empty', SEVERITY.FAIL, 'Title is empty');

  // Strip leading verb for subject analysis
  const subjectMatch = title.match(/^(?:\w+ing\s+)?(.+)$/i);
  const subject = subjectMatch ? subjectMatch[1] : title;

  if (isGenericSubject(subject)) {
    return finding('title_subject_generic', SEVERITY.FAIL,
      `Title subject is generic: "${subject}"`, { subject, title });
  }

  const specificity = scoreSubjectSpecificity(subject);
  if (specificity < 0.20) {
    return finding('title_low_specificity', SEVERITY.FAIL,
      `Title specificity score too low: ${Math.round(specificity * 100)}%`, { specificity, title });
  }
  if (specificity < 0.35) {
    return finding('title_low_specificity_warn', SEVERITY.WARN,
      `Title specificity is marginal: ${Math.round(specificity * 100)}%`, { specificity, title });
  }

  return finding('title_specificity', SEVERITY.PASS, `Title specificity: ${Math.round(specificity * 100)}%`);
}

function checkTitleLength(title = '') {
  const words = title.trim().split(/\s+/).length;
  if (words < 2) {
    return finding('title_too_short', SEVERITY.WARN, `Title has only ${words} word(s)`, { words });
  }
  if (words > 9) {
    return finding('title_too_long', SEVERITY.WARN, `Title is too long (${words} words)`, { words });
  }
  return finding('title_length', SEVERITY.PASS, `Title length: ${words} words`);
}

function checkDescriptionOpeners(description = '') {
  if (!description) return finding('desc_empty', SEVERITY.WARN, 'Description is empty');

  const firstSentence = description.split(/\.\s+/)[0] || description;

  for (const pattern of BLOCKED_DESC_OPENERS) {
    if (pattern.test(firstSentence.trim())) {
      return finding('desc_bad_opener', SEVERITY.FAIL,
        `Description starts with blocked opener: "${firstSentence.slice(0, 60)}"`, { firstSentence });
    }
  }

  return finding('desc_openers', SEVERITY.PASS, 'Description opener is acceptable');
}

function checkDescriptionGenericity(description = '') {
  if (!description) return finding('desc_empty', SEVERITY.WARN, 'Description is empty');

  for (const pattern of GENERIC_DESC_PATTERNS) {
    if (pattern.test(description)) {
      return finding('desc_generic_pattern', SEVERITY.FAIL,
        `Description contains generic pattern: "${pattern.toString()}"`, { description });
    }
  }

  return finding('desc_genericity', SEVERITY.PASS, 'Description contains no generic patterns');
}

function checkClauseStacking(description = '') {
  if (!description) return finding('desc_empty', SEVERITY.WARN, 'Description is empty');

  const matches = description.match(CLAUSE_STACKING_RE);
  if (matches && matches.length >= 3) {
    return finding('clause_stacking', SEVERITY.FAIL,
      `Description stacks ${matches.length} verb clauses — reads robotically`, { matches });
  }
  if (matches && matches.length >= 2) {
    return finding('clause_stacking_warn', SEVERITY.WARN,
      `Description stacks ${matches.length} verb clauses`, { matches });
  }

  return finding('clause_structure', SEVERITY.PASS, 'No excessive clause stacking detected');
}

function checkDescriptionLength(description = '') {
  if (!description) return finding('desc_empty', SEVERITY.WARN, 'Description is empty');

  const words = description.trim().split(/\s+/).length;
  if (words > 60) {
    return finding('desc_too_long', SEVERITY.WARN, `Description is very long (${words} words)`, { words });
  }
  if (words < 6) {
    return finding('desc_too_short', SEVERITY.WARN, `Description is very short (${words} words)`, { words });
  }

  return finding('desc_length', SEVERITY.PASS, `Description length: ${words} words`);
}

function checkRepetition(title = '', description = '') {
  if (!title || !description) return finding('repetition_skip', SEVERITY.PASS, 'Skipped — missing input');

  const titleWords = new Set(
    title.toLowerCase().split(/\s+/).filter(w => w.length >= 5)
  );
  const descWords = description.toLowerCase().split(/\s+/).filter(w => w.length >= 5);

  const repeatedWords = descWords.filter(w => titleWords.has(w));
  const repetitionRate = titleWords.size > 0 ? repeatedWords.length / titleWords.size : 0;

  // The absolute-count floor used to be a fixed 4, but titles in this app are
  // short (2-9 words, often only 2-4 words long enough to count here at all),
  // so near-total duplication could never reach 4 repeated words and silently
  // passed. Scale the floor to the title's own word count instead.
  const repetitionFloor = Math.min(titleWords.size, 2);
  if (repetitionRate >= 0.80 && repeatedWords.length >= repetitionFloor) {
    return finding('high_repetition', SEVERITY.WARN,
      `Description repeats ${Math.round(repetitionRate * 100)}% of title words`, { repetitionRate });
  }

  return finding('repetition', SEVERITY.PASS,
    `Repetition rate: ${Math.round(repetitionRate * 100)}%`);
}

function checkAttributionMatch(title = '', ownership = null) {
  if (!ownership) return finding('attribution_skip', SEVERITY.PASS, 'No ownership context provided');

  // Only check if ownership is high-confidence
  if (!ownership.isHighConfidence || !ownership.subject) {
    return finding('attribution_low_conf', SEVERITY.PASS, 'Ownership confidence too low to validate attribution');
  }

  const ownershipWords = new Set(
    ownership.subject.toLowerCase().split(/\s+/).filter(w => w.length >= 4)
  );
  const titleLower = title.toLowerCase();

  // Check if any ownership word appears in the title
  const hasOwnershipWord = [...ownershipWords].some(w => titleLower.includes(w));

  if (!hasOwnershipWord && ownershipWords.size >= 2) {
    return finding('attribution_mismatch', SEVERITY.WARN,
      `Title "${title}" does not reflect ownership subject "${ownership.subject}"`,
      { ownershipSubject: ownership.subject });
  }

  return finding('attribution', SEVERITY.PASS, 'Title reflects workflow ownership');
}

function checkConfidenceGate(ownership = null) {
  if (!ownership) return finding('confidence_skip', SEVERITY.PASS, 'No ownership to gate on');

  const conf = ownership.confidence || 0;

  if (conf < 0.30) {
    return finding('confidence_too_low', SEVERITY.FAIL,
      `Narrative confidence is critically low (${Math.round(conf * 100)}%) — output would be a guess`,
      { confidence: conf });
  }
  if (conf < 0.50) {
    return finding('confidence_low', SEVERITY.WARN,
      `Narrative confidence is low (${Math.round(conf * 100)}%)`,
      { confidence: conf });
  }

  return finding('confidence', SEVERITY.PASS, `Confidence: ${Math.round(conf * 100)}%`);
}

// ─── Validation Runner ────────────────────────────────────────────────────────

/**
 * @param {Object} narrative   - { title, description, productivityNote? }
 * @param {Object} ownership   - from workflowOwnershipEngine.determineOwnership()
 * @param {Object} options     - { strict: boolean }  strict=true requires no WARNs to pass
 * @returns {QAReport}
 */
export function validateNarrative(narrative = {}, ownership = null, options = {}) {
  const { title = '', description = '' } = narrative;
  const { strict = false } = options;

  const checks = [
    // Title checks
    checkTitleGenericity(title),
    checkTitleSpecificity(title),
    checkTitleLength(title),

    // Description checks
    checkDescriptionOpeners(description),
    checkDescriptionGenericity(description),
    checkClauseStacking(description),
    checkDescriptionLength(description),

    // Cross-field checks
    checkRepetition(title, description),
    checkAttributionMatch(title, ownership),
    checkConfidenceGate(ownership),
  ];

  const failures = checks.filter(c => c.severity === SEVERITY.FAIL);
  const warnings = checks.filter(c => c.severity === SEVERITY.WARN);
  const passes   = checks.filter(c => c.severity === SEVERITY.PASS);

  // Compute an overall quality score (0-1)
  const penaltyPerFail = 0.25;
  const penaltyPerWarn = 0.08;
  const rawPenalty = Math.min(
    failures.length * penaltyPerFail + warnings.length * penaltyPerWarn,
    1.0
  );
  const qualityScore = Math.max(0, 1.0 - rawPenalty);

  // Pass threshold
  const PASS_THRESHOLD = strict ? 0.75 : 0.60;
  const narrativePasses = failures.length === 0 && qualityScore >= PASS_THRESHOLD;

  return {
    passes:          narrativePasses,
    qualityScore:    Math.round(qualityScore * 100) / 100,
    failureCount:    failures.length,
    warningCount:    warnings.length,
    findings:        checks,
    failures,
    warnings,
    passes_list:     passes,
    primaryFailure:  failures[0] || null,
    // Human-readable reason for rejection
    rejectReason:    failures.length > 0 ? failures[0].message : null,
  };
}

/**
 * Quick boolean check: is this title acceptable to publish?
 */
export function isTitleAcceptable(title = '', ownership = null) {
  const report = validateNarrative({ title, description: '' }, ownership);
  return report.failures.filter(f =>
    ['title_generic', 'title_robotic', 'title_empty', 'title_subject_generic', 'title_low_specificity'].includes(f.name)
  ).length === 0;
}

/**
 * Score a single title string 0-100 for display in analytics/debugging.
 */
export function scoreTitleQuality(title = '', ownership = null) {
  const report = validateNarrative({ title, description: '' }, ownership);
  return Math.round(report.qualityScore * 100);
}

/**
 * Given a list of candidate titles, return the best one that passes QA.
 */
export function selectBestTitle(candidates = [], ownership = null) {
  const scored = candidates
    .filter(Boolean)
    .map(title => ({ title, score: scoreTitleQuality(title, ownership) }))
    .sort((a, b) => b.score - a.score);

  const passing = scored.find(s => s.score >= 60);
  return passing?.title || scored[0]?.title || null;
}
