/**
 * Session Summary Engine
 * Generates intelligent session recaps, daily summaries, productivity notes,
 * deep work labels, and weekly reports from tracked session data.
 *
 * v3: Uses the unified reasoningOrchestrator pipeline instead of fragmented
 * engine calls, producing human-quality output free of telemetry leakage.
 */

import { analyzeContext, hasMeaningfulTitle, CATEGORY_VERBS } from './eventContextAnalyzer.js';
import { generateTitle, generateDescription } from './eventWritingEngine.js';
import { orchestrateSync } from '../reasoningOrchestrator.js';
import { isAutoGeneratedContent } from './narrativeQAEngine.js';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function fmtDuration(mins) {
  if (!mins || mins <= 0) return '0m';
  const h = Math.floor(mins / 60);
  const m = Math.round(mins % 60);
  if (h === 0) return `${m}m`;
  if (m === 0) return `${h}h`;
  return `${h}h ${m}m`;
}

function fmtTime(unixSec) {
  if (!unixSec) return '';
  const d = typeof unixSec === 'number'
    ? new Date(unixSec < 1e11 ? unixSec * 1000 : unixSec)
    : new Date(unixSec);
  return d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true });
}

function toUnix(val) {
  if (!val) return 0;
  if (typeof val === 'number') return val > 1e10 ? val / 1000 : val;
  const d = new Date(val);
  return isNaN(d) ? 0 : d.getTime() / 1000;
}

function sessionDurationMins(session, capSecs = null) {
  if (session.duration_seconds > 0) return session.duration_seconds / 60;
  const s = toUnix(session.started_at);
  const rawEnd = toUnix(session.ended_at);
  const e = capSecs ? Math.min(rawEnd, capSecs) : rawEnd;
  return e > s ? (e - s) / 60 : 0;
}

function isOnDate(session, dateISO) {
  const s = toUnix(session.started_at);
  if (!s) return false;
  return new Date(s * 1000).toISOString().slice(0, 10) === dateISO;
}

function getSessionTitle(session) {
  return session.title || session.category || 'Session';
}

// ─── Deep Work Label ──────────────────────────────────────────────────────────

/**
 * Determine the deep work quality label for a session.
 * Returns a human-readable badge string.
 */
export function labelDeepWork(session, autoSessions = []) {
  const durationMins = sessionDurationMins(session);
  const sessStart = toUnix(session.started_at);
  const sessEnd   = toUnix(session.ended_at) || (sessStart + durationMins * 60);
  // Only count switches from auto-sessions that overlap this session's time window
  const overlapping = autoSessions.filter(a => {
    const aStart = toUnix(a.started_at);
    const aEnd   = toUnix(a.ended_at) || aStart;
    return aStart < sessEnd && aEnd > sessStart;
  });
  const contextSwitches = overlapping.reduce((sum, a) => sum + (a.context_switches || 0), 0);
  const isExplicitDeepWork = !!session.is_deep_work;

  if (durationMins >= 90 && contextSwitches < 5) return 'Deep Focus';
  if (durationMins >= 60 && contextSwitches < 10) return 'Focused Work';
  if (isExplicitDeepWork) return 'Deep Work';
  if (durationMins >= 30) return 'Work Session';
  return 'Quick Session';
}

// ─── Session-Level Recap ──────────────────────────────────────────────────────

/**
 * Generate a rich recap for a single completed session.
 *
 * @param {Object} session      - manual session record
 * @param {Array}  autoSessions - auto-tracked sessions during this window
 * @param {Object} [project]    - { id, name }
 * @param {Object} [client]     - { id, name }
 * @returns {Object} Session recap
 */
/**
 * Detect whether a description was auto-generated (and therefore safe to regenerate).
 * Manually written descriptions are preserved; auto-generated ones get upgraded.
 */
export function isAutoGeneratedDescription(desc = '') {
  if (!desc || desc.trim().length < 5) return true;
  const d = desc.trim();

  // Delegate to the canonical shared implementation (narrativeQAEngine.isAutoGeneratedContent)
  // so this and reasoningOrchestrator.isManuallyWrittenDesc() use identical base patterns.
  // Additional sessionSummaryEngine-specific signals follow below.
  if (isAutoGeneratedContent(d)) return true;

  // New-engine output signatures not in the shared set (session-summary-specific formats)
  if (/^(Deep focus session|focused session)\s*[—–]/i.test(d)) return true;
  if (/,\s*with AI assistance\.$/.test(d)) return true;
  if (/\bClient:\s*\w/i.test(d) && d.length < 60) return true; // short client-only note

  // Very short = auto-generated placeholder
  if (d.length < 40) return true;
  return false;
}

export function generateSessionRecap(session, autoSessions = [], project = null, client = null) {
  const durationMins = sessionDurationMins(session);
  const startUnix    = toUnix(session.started_at);
  const endUnix      = toUnix(session.ended_at);

  // Build legacy context (for app/website summaries and backward compatibility)
  const context = analyzeContext({
    autoSessions,
    session,
    project,
    client,
    durationMins,
  });

  const storedDesc = (session.notes || session.description || '').trim();
  let sessionTitle   = session.title;
  let description    = storedDesc;
  let productivityNote = '';
  let deepWorkLabel  = labelDeepWork(session, autoSessions);

  // ── Unified orchestrator pipeline ─────────────────────────────────────────
  // Runs: sanitize → rank → compress → behavior → features → intent → humanize
  if (autoSessions.length > 0) {
    try {
      const orchestrated = orchestrateSync(autoSessions, {
        project,
        client,
        sessionDurationMins: durationMins,
        sessionId: session.id,
        existing: {
          title:       session.title,
          description: isAutoGeneratedDescription(storedDesc) ? '' : storedDesc,
        },
        useContinuity: false,
      });

      sessionTitle     = orchestrated.title     || sessionTitle;
      description      = orchestrated.description || description;
      productivityNote = orchestrated.productivityNote || '';
      deepWorkLabel    = orchestrated.deepWorkLabel    || deepWorkLabel;
    } catch (e) {
      // Silent fallback — legacy engine handles gap below
    }
  }

  // ── Legacy fallback (no autoSessions or orchestrator threw) ──────────────
  if (!hasMeaningfulTitle(sessionTitle)) {
    sessionTitle = generateTitle(context).title;
  }
  if (!description || description.length < 10) {
    description = generateDescription(context, sessionTitle).description;
  }
  if (!productivityNote) {
    productivityNote = buildProductivityNote(context, durationMins);
  }

  // App usage summary
  const topApps = context.apps.slice(0, 4).map(a => ({
    name: a.name,
    mins: Math.round(a.durationSecs / 60),
    pct:  context.totalSecs > 0 ? Math.round((a.durationSecs / context.totalSecs) * 100) : 0,
    category: a.category,
  }));

  // Website usage summary
  const topSites = context.websites.slice(0, 3).map(w => ({
    domain: w.domain,
    topic: w.topic,
    mins: Math.round(w.durationSecs / 60),
  }));

  // Tags: use window title phrases as primary tags
  const tags = context.windowTitlePhrases
    ? context.windowTitlePhrases.slice(0, 3).map(p => p.phrase)
    : (context.fallbackKeywords || []).slice(0, 6);

  return {
    sessionId:      session.id,
    title:          sessionTitle,
    description,
    deepWorkLabel,
    productivityNote,

    // Time
    startTime:      fmtTime(startUnix),
    endTime:        fmtTime(endUnix),
    durationMins:   Math.round(durationMins),
    durationLabel:  fmtDuration(durationMins),

    // Usage
    topApps,
    topSites,
    tags,

    // Classification
    category:       context.primaryCategory,
    isDeepWork:     context.isDeepWork,
    focusQuality:   context.focusQuality,
    contextSwitches: context.contextSwitches,

    // Project / Client
    project,
    client,
  };
}

function buildProductivityNote(context, durationMins) {
  const { focusQuality, isDeepWork, contextSwitches, primaryCategory, primaryApp, workSubtype } = context;
  const dur = Math.round(durationMins);

  // Workflow-first labels — describe the activity, not just the category
  const subtypeLabels = {
    debugging:    'debugging and problem resolution',
    testing:      'testing and quality validation',
    refactoring:  'refactoring and code improvement',
    designing:    'UI design and interaction work',
    researching:  'technical analysis and research',
    reviewing:    'code review and architecture assessment',
    documenting:  'documentation and technical writing',
    planning:     'architecture planning and scoping',
    implementing: 'feature implementation',
    integrating:  'integration and system configuration',
    deploying:    'deployment and release',
  };
  const subtypeLabel = subtypeLabels[workSubtype] || null;

  const durationLabel = (() => {
    const h = Math.floor(dur / 60), m = dur % 60;
    return h > 0 ? (m > 0 ? `${h}h ${m}m` : `${h}h`) : `${dur}m`;
  })();

  if (isDeepWork && focusQuality === 'high') {
    return subtypeLabel
      ? `Deep focus — ${durationLabel} of ${subtypeLabel} with minimal interruptions.`
      : `Deep focus — ${durationLabel} of sustained, high-quality work.`;
  }
  if (isDeepWork && focusQuality === 'medium') {
    return `Focused ${durationLabel} session with solid concentration.`;
  }
  if (contextSwitches > 20) {
    return `Exploratory ${durationLabel} session — high context-switching (${contextSwitches} switches). Consider batching similar tasks.`;
  }
  if (durationMins >= 90) {
    return `Extended ${durationLabel} of ${subtypeLabel || (primaryCategory === 'development' ? 'implementation work' : primaryCategory + ' work')}.`;
  }
  return `${durationLabel} ${subtypeLabel || (primaryCategory === 'development' ? 'implementation session' : primaryCategory + ' session')}.`;
}

// ─── Daily Summary ────────────────────────────────────────────────────────────

/**
 * Generate a comprehensive daily summary from all sessions and auto-sessions.
 *
 * @param {Date}   date
 * @param {Array}  sessions      - manual sessions for the day
 * @param {Array}  autoSessions  - all auto-tracked sessions for the day
 * @param {Array}  calEvents     - calendar events for the day
 * @param {Array}  projects
 * @param {Array}  clients
 * @returns {Object} Daily summary
 */
export function generateDailySummary(date, sessions = [], autoSessions = [], calEvents = [], projects = [], clients = []) {
  const now = new Date();
  const nowSecs = now.getTime() / 1000;
  const dateISO = date.toISOString().slice(0, 10);
  const isToday = dateISO === now.toISOString().slice(0, 10);
  const capSecs = isToday ? nowSecs : null; // cap durations to now for today's sessions

  const dateStr = date.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' });

  // Filter sessions to only those that started on the selected date
  const daySessions = sessions.filter(s => {
    const start = toUnix(s.started_at);
    if (!start) return false;
    if (start * 1000 > now.getTime() && isToday) return false; // skip future sessions today
    return new Date(start * 1000).toISOString().slice(0, 10) === dateISO;
  });
  const dayAutoSessions = autoSessions.filter(s => isOnDate(s, dateISO));

  // Total tracked time
  const totalMins = daySessions.reduce((sum, s) => sum + sessionDurationMins(s, capSecs), 0);

  // Category breakdown
  const byCategory = {};
  for (const s of daySessions) {
    const cat = s.category || s.ai_category || 'other';
    byCategory[cat] = (byCategory[cat] || 0) + sessionDurationMins(s, capSecs);
  }
  const categoryBreakdown = Object.entries(byCategory)
    .sort(([, a], [, b]) => b - a)
    .map(([cat, mins]) => ({ category: cat, mins: Math.round(mins), label: formatCategory(cat) }));

  // Deep work analysis
  const deepWorkSessions = daySessions.filter(s => s.is_deep_work);
  const deepWorkMins = deepWorkSessions.reduce((sum, s) => sum + sessionDurationMins(s, capSecs), 0);
  const deepWorkPct = totalMins > 0 ? Math.round((deepWorkMins / totalMins) * 100) : 0;

  // Context switches
  const totalSwitches = dayAutoSessions.reduce((sum, a) => sum + (a.context_switches || 0), 0);

  // Project breakdown
  const byProject = {};
  for (const s of daySessions) {
    if (!s.project_id) continue;
    const proj = projects.find(p => p.id === s.project_id);
    const name = proj?.name || s.project_id;
    byProject[name] = (byProject[name] || 0) + sessionDurationMins(s, capSecs);
  }
  const projectBreakdown = Object.entries(byProject)
    .sort(([, a], [, b]) => b - a)
    .map(([name, mins]) => ({ name, mins: Math.round(mins) }));

  // App usage
  const appUsage = buildAppUsageFromAutoSessions(dayAutoSessions).slice(0, 5);

  // Session highlights (most productive individual blocks)
  const highlights = daySessions
    .filter(s => sessionDurationMins(s, capSecs) >= 30)
    .sort((a, b) => sessionDurationMins(b, capSecs) - sessionDurationMins(a, capSecs))
    .slice(0, 3)
    .map(s => ({
      title: getSessionTitle(s),
      durationMins: Math.round(sessionDurationMins(s, capSecs)),
      isDeepWork: !!s.is_deep_work,
      startTime: fmtTime(toUnix(s.started_at)),
    }));

  // Summary narrative
  const narrative = buildDailyNarrative({
    dateStr, totalMins, deepWorkMins, deepWorkPct,
    categoryBreakdown, totalSwitches, sessions: daySessions, projects,
  });

  // AI productivity insights
  const insights = buildDailyInsights({
    totalMins, deepWorkMins, deepWorkPct, totalSwitches, sessions: daySessions, categoryBreakdown,
  });

  return {
    date: date.toISOString().slice(0, 10),
    dateLabel: dateStr,
    totalMins: Math.round(totalMins),
    totalLabel: fmtDuration(totalMins),
    deepWorkMins: Math.round(deepWorkMins),
    deepWorkPct,
    totalSessions: daySessions.length,
    totalContextSwitches: totalSwitches,
    categoryBreakdown,
    projectBreakdown,
    appUsage,
    highlights,
    narrative,
    insights,
  };
}

function formatCategory(cat = '') {
  const map = {
    development: 'Development', design: 'Design', writing: 'Writing',
    research: 'Research', meeting: 'Meetings', planning: 'Planning',
    email: 'Email', communication: 'Communication', learning: 'Learning',
    data: 'Data Analysis', admin: 'Admin', break: 'Break',
  };
  return map[cat.toLowerCase()] || cat.charAt(0).toUpperCase() + cat.slice(1);
}

function buildAppUsageFromAutoSessions(autoSessions) {
  const totals = {};
  for (const s of autoSessions) {
    if (s.is_idle) continue;
    const app = s.app_name || '';
    if (!app) continue;
    const dur = s.duration_seconds || 0;
    totals[app] = (totals[app] || 0) + dur;
  }
  return Object.entries(totals)
    .sort(([, a], [, b]) => b - a)
    .map(([name, secs]) => ({ name, mins: Math.round(secs / 60) }));
}

function buildDailyNarrative({ dateStr, totalMins, deepWorkMins, deepWorkPct, categoryBreakdown, totalSwitches, sessions }) {
  if (totalMins < 10) return `Light work day on ${dateStr}.`;

  const topCat = categoryBreakdown[0];
  const hours = Math.round(totalMins / 60 * 10) / 10;
  const deepHours = Math.round(deepWorkMins / 60 * 10) / 10;

  let text = `On ${dateStr}, you tracked ${hours}h of work`;

  if (deepWorkPct >= 40) {
    text += ` with strong deep work discipline — ${deepWorkPct}% in focused sessions.`;
  } else if (deepHours > 0) {
    text += `, including ${deepHours}h of deep work (${deepWorkPct}%).`;
  } else {
    text += '.';
  }

  if (topCat) {
    text += ` Primary focus area: ${topCat.label} (${Math.round(topCat.mins)}m).`;
  }

  if (totalSwitches > 30) {
    text += ` High context-switching (${totalSwitches} switches) may have impacted sustained focus.`;
  }

  return text;
}

function buildDailyInsights({ totalMins, deepWorkMins, deepWorkPct, totalSwitches, sessions, categoryBreakdown }) {
  const insights = [];

  if (deepWorkPct >= 50) {
    insights.push({ type: 'positive', icon: '⚡', text: `Exceptional deep work day — ${deepWorkPct}% focused sessions` });
  } else if (deepWorkPct < 20 && totalMins > 120) {
    insights.push({ type: 'tip', icon: '💡', text: 'Low deep work ratio. Schedule 90-min uninterrupted blocks.' });
  }

  if (totalMins > 600) {
    insights.push({ type: 'warning', icon: '⚠️', text: `Long day — ${Math.round(totalMins / 60)}h tracked. Make sure to rest.` });
  }

  if (totalSwitches > 40) {
    insights.push({ type: 'warning', icon: '🔄', text: `High context-switching (${totalSwitches}). Batch similar tasks together.` });
  }

  const meetingCat = categoryBreakdown.find(c => c.category === 'meeting');
  if (meetingCat && meetingCat.mins > 180) {
    insights.push({ type: 'warning', icon: '📅', text: `${Math.round(meetingCat.mins / 60)}h in meetings. Protect focus blocks.` });
  }

  return insights.slice(0, 3);
}

// ─── Weekly Summary ───────────────────────────────────────────────────────────

/**
 * Generate a weekly summary from daily sessions.
 *
 * @param {Date}  weekStart
 * @param {Array} sessions        - all sessions for the week
 * @param {Array} autoSessions    - all auto-sessions for the week
 * @param {Array} projects
 * @returns {Object} Weekly summary
 */
export function generateWeeklySummary(weekStart, sessions = [], autoSessions = [], projects = []) {
  const weekEnd = new Date(weekStart);
  weekEnd.setDate(weekEnd.getDate() + 6);

  const totalMins = sessions.reduce((sum, s) => sum + sessionDurationMins(s), 0);
  const deepWorkMins = sessions.filter(s => s.is_deep_work)
    .reduce((sum, s) => sum + sessionDurationMins(s), 0);
  const deepWorkPct = totalMins > 0 ? Math.round((deepWorkMins / totalMins) * 100) : 0;

  // Days worked
  const workedDays = new Set(sessions.map(s => {
    const d = new Date(toUnix(s.started_at) * 1000);
    return d.toISOString().slice(0, 10);
  })).size;

  // Avg per day
  const avgDailyMins = workedDays > 0 ? totalMins / workedDays : 0;

  // Top projects
  const projectTime = {};
  for (const s of sessions) {
    if (!s.project_id) continue;
    projectTime[s.project_id] = (projectTime[s.project_id] || 0) + sessionDurationMins(s);
  }
  const topProjects = Object.entries(projectTime)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 5)
    .map(([id, mins]) => {
      const proj = projects.find(p => p.id === id);
      return { name: proj?.name || id, mins: Math.round(mins) };
    });

  // Top apps for the week
  const appUsage = buildAppUsageFromAutoSessions(autoSessions).slice(0, 6);

  // Best day
  const dayTotals = {};
  for (const s of sessions) {
    const d = new Date(toUnix(s.started_at) * 1000).toISOString().slice(0, 10);
    dayTotals[d] = (dayTotals[d] || 0) + sessionDurationMins(s);
  }
  const bestDay = Object.entries(dayTotals).sort(([, a], [, b]) => b - a)[0];

  // Total context switches
  const totalSwitches = autoSessions.reduce((sum, a) => sum + (a.context_switches || 0), 0);

  // Achievements
  const achievements = buildWeeklyAchievements({ totalMins, deepWorkMins, deepWorkPct, workedDays, avgDailyMins });

  return {
    weekStart:       weekStart.toISOString().slice(0, 10),
    weekEnd:         weekEnd.toISOString().slice(0, 10),
    totalMins:       Math.round(totalMins),
    totalHours:      Math.round(totalMins / 60 * 10) / 10,
    totalLabel:      fmtDuration(totalMins),
    deepWorkMins:    Math.round(deepWorkMins),
    deepWorkPct,
    workedDays,
    avgDailyMins:    Math.round(avgDailyMins),
    avgDailyLabel:   fmtDuration(avgDailyMins),
    totalSessions:   sessions.length,
    totalSwitches,
    topProjects,
    appUsage,
    bestDay: bestDay ? { date: bestDay[0], mins: Math.round(bestDay[1]) } : null,
    achievements,
    narrative: buildWeeklyNarrative({ totalMins, deepWorkPct, workedDays, topProjects, avgDailyMins }),
  };
}

function buildWeeklyAchievements({ totalMins, deepWorkMins, deepWorkPct, workedDays, avgDailyMins }) {
  const achievements = [];
  if (totalMins >= 40 * 60) achievements.push({ icon: '🔥', text: '40+ hour work week' });
  if (deepWorkPct >= 40)     achievements.push({ icon: '⚡', text: `${deepWorkPct}% deep work ratio` });
  if (deepWorkMins >= 10 * 60) achievements.push({ icon: '🎯', text: '10h+ of deep work' });
  if (workedDays >= 5)       achievements.push({ icon: '📅', text: 'Full 5-day week' });
  if (avgDailyMins >= 8 * 60) achievements.push({ icon: '💪', text: 'Averaging 8h/day' });
  return achievements;
}

function buildWeeklyNarrative({ totalMins, deepWorkPct, workedDays, topProjects, avgDailyMins }) {
  const hours = Math.round(totalMins / 60 * 10) / 10;
  const avgH  = Math.round(avgDailyMins / 60 * 10) / 10;
  const mainProj = topProjects[0]?.name;

  let text = `This week you logged ${hours}h across ${workedDays} work day${workedDays !== 1 ? 's' : ''} (avg ${avgH}h/day).`;

  if (deepWorkPct >= 40) {
    text += ` Excellent deep work focus at ${deepWorkPct}% of total time.`;
  } else if (deepWorkPct > 0) {
    text += ` Deep work made up ${deepWorkPct}% of your time.`;
  }

  if (mainProj) {
    text += ` Primary project: ${mainProj}.`;
  }

  return text;
}

// ─── AI Productivity Note ─────────────────────────────────────────────────────

/**
 * Generate a short AI productivity note for a session or time block.
 * Used in session detail popups and tooltips.
 *
 * @param {Object} session
 * @param {Array}  autoSessions
 * @param {Object} context - from analyzeContext (optional, avoids recomputing)
 * @returns {string}
 */
export function generateProductivityNote(session, autoSessions = [], context = null) {
  const durationMins = sessionDurationMins(session);
  const dur = Math.round(durationMins);

  // Try using orchestrator for richer note when auto-sessions available
  if (autoSessions.length > 0) {
    try {
      const orchestrated = orchestrateSync(autoSessions, {
        sessionDurationMins: durationMins,
        useContinuity: false,
      });
      if (orchestrated.productivityNote) return orchestrated.productivityNote;
    } catch {}
  }

  const ctx = context || analyzeContext({ autoSessions, session });

  if (ctx.focusQuality === 'high' && durationMins >= 60) {
    return `Deep focus session — ${dur} min, ${ctx.contextSwitches} context switches.`;
  }
  if (ctx.contextSwitches > 20) {
    return `Fragmented session — ${ctx.contextSwitches} context switches. Consider batching tasks.`;
  }
  if (ctx.primaryApp) {
    return `${dur}-min ${ctx.primaryCategory} session — primary tool: ${ctx.primaryApp}.`;
  }
  return `${dur}-min ${ctx.primaryCategory} session.`;
}

// ─── Smart Session Title Suggestions ─────────────────────────────────────────

/**
 * Suggest titles for a session based on what's running right now.
 * Used for real-time suggestions while a session is in progress.
 *
 * @param {Array}  liveAutoSessions - auto-sessions from the last 30 min
 * @param {Object} project
 * @param {Object} client
 * @returns {string[]} Up to 4 title suggestions
 */
export function suggestLiveTitles(liveAutoSessions = [], project = null, client = null) {
  if (!liveAutoSessions.length) return [];

  try {
    const orchestrated = orchestrateSync(liveAutoSessions, { project, client });
    const suggestions = [orchestrated.title].filter(Boolean);

    // Add intent-based alternate from the humanized output
    const humanized = orchestrated.humanized;
    if (humanized?.activityPhrase) {
      const altVerb = orchestrated.intent?.verbs?.[1] || 'Building';
      const alt = `${altVerb} ${humanized.activityPhrase}`;
      if (alt !== orchestrated.title) suggestions.push(alt.slice(0, 68));
    }

    // Project-specific suggestion
    if (project?.name && !suggestions.some(s => s.toLowerCase().includes(project.name.toLowerCase()))) {
      const verb = orchestrated.intent?.type === 'debugging' ? 'Debugging' : 'Building';
      suggestions.push(`${verb} ${project.name}`);
    }

    return [...new Set(suggestions)].filter(Boolean).slice(0, 4);
  } catch {
    // Legacy fallback
    const context = analyzeContext({ autoSessions: liveAutoSessions, project, client });
    const { title, alternates } = generateTitle(context);
    const suggestions = [title, ...alternates].filter(Boolean);
    if (project?.name && !suggestions.some(s => s.includes(project.name))) {
      const verb = (CATEGORY_VERBS[context.primaryCategory] || CATEGORY_VERBS.research)[0];
      suggestions.push(`${verb} ${project.name}`);
    }
    return [...new Set(suggestions)].slice(0, 4);
  }
}
